### ISSUE TITLE
BatchDownload isn't working on Windows

### ISSUE THREAD

**Issue by mvanzalu** [ICIJ/datashare#1008]
**Describe the bug**
When launching a Batch Download, an error is raised with the following message.

```
2023-01-25 17:41:11,408 [Worker: RequestDispatcher: Thread-26] ERROR Fluent - Unable to POST /api/task/batchDownload
2023-01-25 17:41:11,417 [Worker: RequestDispatcher: Thread-26] ERROR Fluent - Unexpected error:
java.nio.file.InvalidPathException: Illegal char <:> at index 27: archive_local_2023-01-25T16:41:11.408Z[GMT].zip
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at org.icij.datashare.batch.BatchDownload.createFilename(BatchDownload.java:91)
        at org.icij.datashare.batch.BatchDownload.<init>(BatchDownload.java:53)
        at org.icij.datashare.web.TaskResource.batchDownload(TaskResource.java:149)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at net.codestory.http.routes.ReflectionRoute.invoke(ReflectionRoute.java:83)
        at net.codestory.http.routes.ReflectionRoute.lambda$body$0(ReflectionRoute.java:45)
        at net.codestory.http.annotations.MethodAnnotations.apply(MethodAnnotations.java:48)
        at net.codestory.http.routes.ReflectionRoute.body(ReflectionRoute.java:40)
        at net.codestory.http.routes.RouteWithPattern.body(RouteWithPattern.java:56)
        at net.codestory.http.routes.Route.apply(Route.java:25)
        at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$98caf044$1(RouteCollection.java:577)
        at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
        at org.icij.datashare.session.LocalUserFilter.otherUri(LocalUserFilter.java:30)
        at net.codestory.http.filters.auth.CookieAuthFilter.apply(CookieAuthFilter.java:78)
        at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
        at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
        at org.icij.datashare.web.IndexWaiterFilter.apply(IndexWaiterFilter.java:44)
        at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
        at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
        at org.icij.datashare.session.LocalUserFilter.otherUri(LocalUserFilter.java:30)
        at net.codestory.http.filters.auth.CookieAuthFilter.apply(CookieAuthFilter.java:78)
        at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
        at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
        at org.icij.datashare.web.IndexWaiterFilter.apply(IndexWaiterFilter.java:44)
        at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
        at net.codestory.http.routes.RouteCollection.apply(RouteCollection.java:567)
        at net.codestory.http.AbstractWebServer.handleHttp(AbstractWebServer.java:152)
        at net.codestory.http.internal.SimpleServerWrapper.handle(SimpleServerWrapper.java:71)
        at org.simpleframework.http.socket.service.RouterContainer.handle(RouterContainer.java:106)
        at org.simpleframework.http.core.RequestDispatcher.dispatch(RequestDispatcher.java:121)
        at org.simpleframework.http.core.RequestDispatcher.run(RequestDispatcher.java:103)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
2023-01-25 17:43:53,705 [elasticsearch[datashare][transport_worker][T#1]] WARN  DateHistogramAggregationBuilder - [interval] on [date_histogram] is deprecated, use [fixed_interval] or [calendar_interval] in the future.
2023-01-25 17:44:02,824 [Worker: RequestDispatcher: Thread-30] INFO  Plugin - downloading from url https://github.com/ICIJ/datashare-plugin-dataconnect/releases/download/1.5.2/datashare-plugin-dataconnect-1.5.2.tgz
2023-01-25 17:44:02,964 [Worker: RequestDispatcher: Thread-30] INFO  Plugin - installing plugin from file C:\Users\IEUser\AppData\Local\Temp\tmp17474802755695010697.tgz into C:\Users\IEUser\AppData\Roaming\Datashare\plugins
2023-01-25 17:44:05,272 [Worker: RequestDispatcher: Thread-31] INFO  Extension - downloading from url https://github.com/ICIJ/datashare-extension-dataconnect/releases/download/0.0.10/datashare-extension-dataconnect-0.0.10-jar-with-dependencies.jar
2023-01-25 17:44:06,739 [Worker: RequestDispatcher: Thread-31] INFO  Extension - installing extension from file C:\Users\IEUser\AppData\Local\Temp\tmp13580665565758547149.jar into C:\Users\IEUser\AppData\Roaming\Datashare\extensions
```
It seems we have path name incompatibilty on Windows, the generated zip archive name contains `:` which is forbidden in Windows. Nevertheless, java should manage this.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 10.5.2

**Comment by mvanzalu** [comment]
Datashare-api [pull request](https://github.com/ICIJ/datashare-api/pull/10)

**Comment by mvanzalu** [comment]
Datashare [pull request](https://github.com/ICIJ/datashare/pull/1011)
