### ISSUE TITLE
Exception in SCAN,INDEX job while opening .cdr file

### ISSUE THREAD

**Issue by bolek2000** [ICIJ/datashare#1285]
`docker compose exec datashare_web /entrypoint.sh   --mode CLI   --stage SCAN,INDEX   --defaultProject myproject --elasticsearchAddress http://elasticsearch:9200   --dataDir /home/datashare/Datashare/`

 job exits with Exception:

```
2023-12-31 12:02:45,217 [pool-5-thread-20] ERROR DocumentConsumer - Exception while consuming file: "/home/datashare/Datashare/private_filename.cdr".
java.io.IOException: 
        at org.apache.tika.parser.ParsingReader.read(ParsingReader.java:237)
        at java.base/java.io.Reader.read(Unknown Source)
        at org.icij.spewer.Spewer.copy(Spewer.java:121)
        at org.icij.spewer.Spewer.toString(Spewer.java:131)
        at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchSpewer.getDocumentMap(ElasticsearchSpewer.java:135)
        at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchSpewer.prepareRequest(ElasticsearchSpewer.java:90)
        at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchSpewer.writeDocument(ElasticsearchSpewer.java:66)
        at org.icij.spewer.Spewer.write(Spewer.java:56)
        at org.icij.extract.extractor.Extractor.extract(Extractor.java:271)
        at org.icij.extract.extractor.DocumentConsumer.lambda$accept$0(DocumentConsumer.java:126)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.tika.exception.TikaException: Parse error
        at org.apache.tika.parser.ErrorParser.parse(ErrorParser.java:47)
        at org.icij.extract.parser.FallbackParser.parse(FallbackParser.java:53)
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
        at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:167)
        at org.apache.tika.parser.ParserDecorator.parse(ParserDecorator.java:152)
        at org.apache.tika.parser.DigestingParser.parse(DigestingParser.java:55)
        at org.apache.tika.parser.ParsingReader$ParsingTask.run(ParsingReader.java:268)
        ... 1 common frames omitted
```
 

**Expected behavior**
Skip file, write error message and continue job

**Environment**
Docker server install on Debian 11

**Additional context**
`file` command on linux shows following file type:
RIFF (little-endian) data, Corel Draw Picture or template, version 'D' 13, 50978642 bytes

**Comment by bolek2000** [comment]
Just saw that I used an old docker-compose file copied from the docs with datashare 11.1.9 image. I updated file to 13.9.0 and check if the error is still present.

**Comment by bamthomas** [comment]
AFAIK when there is parsing issues with Tika the file is ignored, an error report is generated in the report map.

**Comment by bolek2000** [comment]
Yes, seems this was just at the end of the logfile and I thought the job stopped because of exception, also because we were missing files in the search results. I see now that there are more exceptions and the job continues.
