### ISSUE TITLE
Embedded mode is broken

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#1286]
**Describe the bug**

When running datashare with `-m EMBEDDED` there is an exception thrown preventing datashare to run normally.

**To Reproduce**
1. launch datashare in embedded mode

**Expected behavior**

That embedded mode is running normally with elasticsearch.

**Screenshots**

```shell
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.elasticsearch.http.AbstractHttpServerTransport.<init>(AbstractHttpServerTransport.java:130)
        at org.elasticsearch.http.netty4.Netty4HttpServerTransport.<init>(Netty4HttpServerTransport.java:155)
        at org.elasticsearch.transport.Netty4Plugin.lambda$getHttpTransports$1(Netty4Plugin.java:113)
        at org.elasticsearch.node.Node.newHttpTransport(Node.java:1585)
        at org.elasticsearch.node.Node.<init>(Node.java:814)
        at org.icij.datashare.text.indexing.elasticsearch.EsEmbeddedServer$PluginConfigurableNode.<init>(EsEmbeddedServer.java:81)
        at org.icij.datashare.text.indexing.elasticsearch.EsEmbeddedServer.createNode(EsEmbeddedServer.java:61)
        at org.icij.datashare.text.indexing.elasticsearch.EsEmbeddedServer.<init>(EsEmbeddedServer.java:41)
        at org.icij.datashare.mode.EmbeddedMode.configure(EmbeddedMode.java:16)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
        at com.google.inject.spi.Elements.getElements(Elements.java:110)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at org.icij.datashare.mode.CommonMode.<init>(CommonMode.java:97)
        at org.icij.datashare.mode.LocalMode.<init>(LocalMode.java:13)
        at org.icij.datashare.mode.EmbeddedMode.<init>(EmbeddedMode.java:10)
        at org.icij.datashare.mode.CommonMode.create(CommonMode.java:118)
        at org.icij.datashare.WebApp.start(WebApp.java:36)
        at org.icij.datashare.Main.main(Main.java:20)
Caused by: java.lang.UnsupportedOperationException: No class provided, and an appropriate one cannot be found.
        at org.apache.logging.log4j.LogManager.callerClass(LogManager.java:573)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:598)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:585)
        at org.elasticsearch.http.HttpClientStatsTracker.<clinit>(HttpClientStatsTracker.java:38)
```

**Comment by bamthomas** [comment]
when using the built `datashare-index.jar` and launch ES with it, it works properly.

in the commit https://github.com/ICIJ/datashare/commit/4d6d8821bc50d0c019c82d3e9f4ffa0976bad4db we've added the property:

```
Multi-Release: true
```
In the MANIFEST.MF see [this SO thread](https://stackoverflow.com/questions/53049346/is-log4j2-compatible-with-java-11)

**Comment by bamthomas** [comment]
we found that the commit that has broken the embedded mode is the upgrade of elasticsearch and lucene is the e9b2eee8

**Comment by bamthomas** [comment]
![embeddedModeFails drawio(1)](https://github.com/ICIJ/datashare/assets/551723/a8776459-2d21-4d9f-b8ae-52a4c7000bf9)

**Comment by bamthomas** [comment]
For the record, the diagram above was from the [Mikado Method](https://mikadomethod.info/). It's made to keep track of the different explored branches when facing a difficult problem.

![293987275-a8776459-2d21-4d9f-b8ae-52a4c7000bf9(2)](https://github.com/ICIJ/datashare/assets/551723/8b43f4bd-f539-457c-bd25-7d6b689c0a9b)
