### ISSUE TITLE
feat: As a `USER`, I'd like to be able to migrate my local index and tags to another computer

### ISSUE THREAD

**Issue by jceipek** [ICIJ/datashare#1339]
**Is your feature request related to a problem? Please describe.**
I'm helping a friend analyze data from a FOIA request and initially set up a local Datashare instance on my personal Mac. When I copied `~/Library/Datashare` and `~/Datashare` to my friend's Mac, searching seemed to work properly, but the preview option didn't. I think this is because `/Users/myname/Datashare` doesn't match `/Users/friendsname/Datashare`. In an attempt to rectify this, I created `/Users/myname/Datashare` on my friend's computer with a copy of the same data on my computer and used `ln -s` to symlink each document in `/Users/myname/Datashare/docname` to `/Users/friendsname/Datashare/docname`. This made previews work. However, when I tried to run "Find people, organizations and locations with CoreNLP" from my friend's computer, `EnqueueFromIndexTask` failed almost immediately with no logged error in the console while `ExtractNLPTask` repeatedly spews this in the background and never finishes.
```
2024-02-24 22:34:52,966 [Worker: RequestDispatcher: Thread-40] ERROR TaskView - Task failed for user org.icij.datashare.session.DatashareUser@625df8a :
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Queue full
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.icij.datashare.tasks.TaskView.getResult(TaskView.java:87)
	at org.icij.datashare.tasks.TaskView.getResult(TaskView.java:79)
	at jdk.internal.reflect.GeneratedMethodAccessor280.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:689)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1514)
	at com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1215)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsBytes(ObjectWriter.java:1108)
	at net.codestory.http.convert.TypeConvert.toByteArray(TypeConvert.java:96)
	at net.codestory.http.payload.PayloadWriter.toJson(PayloadWriter.java:413)
	at net.codestory.http.payload.PayloadWriter.getData(PayloadWriter.java:409)
	at net.codestory.http.payload.PayloadWriter.lambda$writeBytes$bebecf81$1(PayloadWriter.java:197)
	at net.codestory.http.payload.DataSupplier$1.get(DataSupplier.java:31)
	at net.codestory.http.payload.PayloadWriter.writeBytes(PayloadWriter.java:201)
	at net.codestory.http.payload.PayloadWriter.write(PayloadWriter.java:192)
	at net.codestory.http.payload.PayloadWriter.writeAndCloseSync(PayloadWriter.java:106)
	at net.codestory.http.payload.PayloadWriter.writeAndClose(PayloadWriter.java:95)
	at net.codestory.http.AbstractWebServer.handleHttp(AbstractWebServer.java:154)
	at net.codestory.http.internal.SimpleServerWrapper.handle(SimpleServerWrapper.java:71)
	at org.simpleframework.http.socket.service.RouterContainer.handle(RouterContainer.java:106)
	at org.simpleframework.http.core.RequestDispatcher.dispatch(RequestDispatcher.java:121)
	at org.simpleframework.http.core.RequestDispatcher.run(RequestDispatcher.java:103)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Describe the solution you'd like**
I'd like to have clear documentation for how to transfer the data and index from one local computer to another (and potentially from one local instance to a server, to make migrating to a collaborative setup easier). I would ideally also like the document paths to be relative rather than absolute so that symlinking isn't necessary.

**Describe alternatives you've considered**
I considered fully recreating my index, tags, favorites, etc... on my friend's computer, but that would take a very long time.

**Comment by pirhoo** [comment]
The memory queue has a hard limit of 1024 simultaneous values (ie. documents to index). In most case that enough because the indexing task is draining documents from this queue before it gets full. In your case, probably because you have a lot of big documents, the indexing task is getting caught up by the scan task.

We are going to increase the limit and use a more lightweight method to store the document paths in the queue.

**Comment by jceipek** [comment]
> The memory queue has a hard limit of 1024 simultaneous values (ie. documents to index). In most cases that's enough because the indexing task is draining documents from this queue before it gets full. In your case, probably because you have a lot of big documents, the indexing task is getting caught up by the scan task.
> 
> We are going to increase the limit and use a more lightweight method to store the document paths in the queue.

Thanks!
