### ISSUE TITLE
Datashare launch command should work without options

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#1367]
**Describe the bug**

We have someone struggling with datashare install on Mac. We wanted to make her start datashare "by hand" with the more minimal command:

```shell
java -Djava.system.class.loader=org.icij.datashare.DynamicClassLoader -cp datashare-dist-14.2.0-all.jar org.icij.datashare.Main
```

But it fails: 

```
Exception in thread "main" com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Unable to load cache item                                                               
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2087)                                                                                                                                    
        at com.google.common.cache.LocalCache.get(LocalCache.java:4036)                                                                                                                                            
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4059)                                                                                                                                      
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5041)                                                                                                                          
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5048)                                                                                                                 
        at com.google.inject.internal.FailableCache.get(FailableCache.java:54)                                                                                                                                     
        at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:49)                                                                                                               
        at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:155)                                                                                                           
        at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:592)                                                                                                                        
        at com.google.inject.internal.AbstractBindingProcessor$Processor.initializeBinding(AbstractBindingProcessor.java:173)                                                                                      
        at com.google.inject.internal.AbstractBindingProcessor$Processor.lambda$scheduleInitialization$0(AbstractBindingProcessor.java:160)                                                                        
        at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:49)                                                                                                        
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:124)                                                                                               
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:108)                                                                                                              
        at com.google.inject.Guice.createInjector(Guice.java:87)                                                                                                                                                   
        at com.google.inject.Guice.createInjector(Guice.java:69)                                                                                                                                                   
        at com.google.inject.Guice.createInjector(Guice.java:59)                                                                                                                                                   
        at org.icij.datashare.mode.CommonMode.<init>(CommonMode.java:85)                                                                                                                                           
        at org.icij.datashare.mode.LocalMode.<init>(LocalMode.java:13)                                                                                                                                             
        at org.icij.datashare.mode.EmbeddedMode.<init>(EmbeddedMode.java:10)                                                                                                                                       
        at org.icij.datashare.mode.CommonMode.create(CommonMode.java:107)                                                                                                                                          
        at org.icij.datashare.WebApp.start(WebApp.java:34)                
```

It is probably caused by a parameter not provided that makes guice IoC failing.

**To Reproduce**
1. download or build a datashare jar
2. execute the above command
3. see it failing

**Expected behavior**

That the command 

```shell
java -Djava.system.class.loader=org.icij.datashare.DynamicClassLoader -cp datashare-dist-14.2.0-all.jar org.icij.datashare.Main
```
works out of the box with embedded mode and memory for bus/queues

Ideally it should work with 
```shell
java -jar datashare.jar
```
(it used to)

**Comment by bamthomas** [comment]
it is also necessary to add the `--add-opens` from the JDK-17 migration into the `MANIFEST.MF` file.
see https://stackoverflow.com/a/76675952/396155
