### ISSUE TITLE
Failed to process "The Enron PST Data Set Cleansed of PII by Nuix and EDRM"

### ISSUE THREAD

**Issue by salevajo** [ICIJ/datashare#142]
You can get the dataset at http://info.nuix.com/Enron.html

Trying to process this dataset "as is" just by copying the Zipfile into a subfolder ~/Datashare/data fails after a short period of time with two exceptions shown in the logs:

```java
2019-05-14 07:22:33,626 [pool-7-thread-1] ERROR DocumentConsumer - Exception while consuming file: "/home/datashare/data/Enron/RevisedEDRMv1_Complete.zip".
java.lang.NumberFormatException: For input string: "19708997129"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:583)
	at java.lang.Integer.valueOf(Integer.java:766)
	at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchSpewer.getMap(ElasticsearchSpewer.java:112)
	at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchSpewer.prepareRequest(ElasticsearchSpewer.java:85)
	at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchSpewer.writeDocument(ElasticsearchSpewer.java:60)
	at org.icij.spewer.Spewer.write(Spewer.java:56)
	at org.icij.extract.extractor.Extractor.extract(Extractor.java:278)
	at org.icij.extract.extractor.DocumentConsumer.lambda$accept$0(DocumentConsumer.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-05-14 07:22:33,651 [pool-3-thread-2] INFO  DocumentConsumer - Terminated.
2019-05-14 07:22:33,746 [pool-3-thread-2] INFO  IndexTask - exiting
2019-05-14 07:22:34,370 [Apache Tika: RevisedEDRMv1_Complete.zip] ERROR EmbedParser - Unable to parse embedded document: "RevisedEDRMv1_Complete/albert_meyers/albert_meyers_000_1_1.pst" (application/vnd.ms-outlook-pst) (in "/home/datashare/data/Enron/RevisedEDRMv1_Complete.zip").
org.apache.tika.exception.TikaException: Parse error
	at org.apache.tika.parser.ErrorParser.parse(ErrorParser.java:49)
	at org.icij.extract.parser.FallbackParser.parse(FallbackParser.java:53)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143)
	at org.apache.tika.parser.ParserDecorator.parse(ParserDecorator.java:188)
	at org.apache.tika.parser.DigestingParser.parse(DigestingParser.java:84)
	at org.apache.tika.parser.DelegatingParser.parse(DelegatingParser.java:72)
	at org.icij.extract.extractor.EmbedParser.delegateParsing(EmbedParser.java:76)
	at org.icij.extract.extractor.EmbedSpawner.spawnEmbedded(EmbedSpawner.java:114)
	at org.icij.extract.extractor.EmbedSpawner.parseEmbedded(EmbedSpawner.java:63)
	at org.apache.tika.parser.pkg.PackageParser.parseEntry(PackageParser.java:350)
	at org.apache.tika.parser.pkg.PackageParser.parse(PackageParser.java:287)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143)
	at org.apache.tika.parser.ParserDecorator.parse(ParserDecorator.java:188)
	at org.apache.tika.parser.DigestingParser.parse(DigestingParser.java:84)
	at org.apache.tika.parser.ParsingReader$ParsingTask.run(ParsingReader.java:235)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by bamthomas** [comment]
Sorry for the late answer, yes it is really likely that this could happen. When we are indexing huge document corpuses, there are still errors that happen with tika. I'm currently downloading the dataset. 

We'll see with the datashare team if we want to improve this, as it could be a very hard work to take every single parsing error and investigate what's going on.

**Comment by bamthomas** [comment]
Also this could be reported to tika as it is a tika parsing issue.

**Comment by bamthomas** [comment]
I'm closing this issue for now because we won't work on this soon.
