### ISSUE TITLE
German exception during Named Entity Extraction

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#146]

**Comment by bamthomas** [comment]
```
2019-05-18 13:23:02,278 [CORENLP-0] INFO  CorenlpPipeline - name-finding for GERMAN
2019-05-18 13:23:05,782 [CORENLP-0] INFO  CoreNlpNerModels - adding models/corenlp/3-9-2/de/stanford-german-corenlp-2018-10-05-models.jar to system classloader
2019-05-18 13:23:05,786 [CORENLP-0] ERROR CoreNlpNerModels - failed loading NER
java.io.IOException: Unable to open "edu/stanford/nlp/models/ner/german.conll.hgc_175m_600.crf.ser.gz" as class path, filename or URL
	at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:480)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1503)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1495)
	at edu.stanford.nlp.ie.crf.CRFClassifier.getClassifier(CRFClassifier.java:2932)
	at org.icij.datashare.text.nlp.corenlp.models.CoreNlpNerModels.loadModelFile(CoreNlpNerModels.java:75)
	at org.icij.datashare.text.nlp.corenlp.models.CoreNlpNerModels.loadModelFile(CoreNlpNerModels.java:39)
	at org.icij.datashare.text.nlp.AbstractModels.load(AbstractModels.java:61)
	at org.icij.datashare.text.nlp.AbstractModels.get(AbstractModels.java:48)
	at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.processNerClassifier(CorenlpPipeline.java:197)
	at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.process(CorenlpPipeline.java:92)
	at org.icij.datashare.text.nlp.NlpConsumer.findNamedEntities(NlpConsumer.java:67)
	at org.icij.datashare.text.nlp.NlpConsumer.run(NlpConsumer.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-05-18 13:23:05,787 [CORENLP-0] WARN  NlpConsumer - error in consumer main loop
java.lang.NullPointerException: null
	at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.processNerClassifier(CorenlpPipeline.java:198)
	at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.process(CorenlpPipeline.java:92)
	at org.icij.datashare.text.nlp.NlpConsumer.findNamedEntities(NlpConsumer.java:67)
	at org.icij.datashare.text.nlp.NlpConsumer.run(NlpConsumer.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
