### ISSUE TITLE
Deserialize error

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#215]
We have an error at 2019-07-24 08:27:40.802 when de serializing document 
faf75afde8f642e4672d8c865f45104e9a07399a008b50d6c16456d125bbb28e

```
parentDocument=24e4b217e7e90bfac33e9e128b837c9200957b9651ddc65abdd56d263ecb6f47, extractionDate=2018-03-13T19:26:30.643Z, path=/vault/shared/hippocrates/Nanostim/Other/Device Focus Group meeting St Jude.docx, id=faf75afde8f642e4672d8c865f45104e9a07399a008b50d6c16456d125bbb28e, contentType=image/jpeg, status=INDEXED}
	at org.icij.datashare.json.JsonObjectMapper.getObject(JsonObjectMapper.java:88)
	at org.icij.datashare.json.JsonObjectMapper.getObject(JsonObjectMapper.java:81)
	at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchIndexer.get(ElasticsearchIndexer.java:189)
	at org.icij.datashare.web.IndexResource.getSourceFile(IndexResource.java:98)
			4 lines skipped for [sun., java.lang.reflect.Method]
	at net.codestory.http.routes.ReflectionRoute.invoke(ReflectionRoute.java:83)
	at net.codestory.http.routes.ReflectionRoute.lambda$body$0(ReflectionRoute.java:45)
	at net.codestory.http.annotations.MethodAnnotations.apply(MethodAnnotations.java:48)
	at net.codestory.http.routes.ReflectionRoute.body(ReflectionRoute.java:40)
	at net.codestory.http.routes.RouteWithPattern.body(RouteWithPattern.java:56)
	at net.codestory.http.routes.Route.apply(Route.java:25)
	at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$98caf044$1(RouteCollection.java:577)
	at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
	at net.codestory.http.filters.auth.CookieAuthFilter.otherUri(CookieAuthFilter.java:103)
	at net.codestory.http.filters.auth.CookieAuthFilter.apply(CookieAuthFilter.java:78)
	at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
	at net.codestory.http.routes.RouteCollection.apply(RouteCollection.java:567)
	at net.codestory.http.AbstractWebServer.handleHttp(AbstractWebServer.java:152)
	at net.codestory.http.internal.SimpleServerWrapper.handle(SimpleServerWrapper.java:71)
	at org.simpleframework.http.socket.service.RouterContainer.handle(RouterContainer.java:106)
	at org.simpleframework.http.core.RequestDispatcher.dispatch(RequestDispatcher.java:121)
	at org.simpleframework.http.core.RequestDispatcher.run(RequestDispatcher.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `org.icij.datashare.text.Language` from String "ROMANIAN": value not one of declared Enum instance names: [KOMI, PASHTO, ZULU, MALAYALAM, CENTRALKHMER, MARSHALLESE, TIGRINYA, WESTERNFRISIAN, POLISH, WELSH, AFRIKAANS, AFAR, BULGARIAN, KAZAKH, SWAHILI, BRETON, LATVIAN, TWI, TELUGU, SLOVAK, BASQUE, PALI, RUNDI, GANDA, KUANYAMA, PORTUGUESE, VOLAPUK, VENDA, INTERLIGUE, VIETNAMESE, FULAH, CHICHEWA, MALAGASY, WOLOF, TONGA, ORIYA, CREE, ENGLISH, ESTONIAN, DZONGKHA, MALDIVIAN, MANX, TAJIK, BASHKIR, ARAGONESE, CROATIAN, WALLOON, LIMBURGAN, GALICIAN, JAVANESE, SOMALI, OROMO, MALAY, SUNDANESE, ZHUANG, SICHUANYI, LAO, SWEDISH, SOUTHNDEBELE, HEBREW, PERSIAN, KIRGHIZ, MOLDAVIAN, DUTCH, SOUTHERNSOTHO, SINDHI, OLDSLAVONIC, TAHITIAN, SWATI, CZECH, KANURI, IRISH, OSSETIAN, FRENCH, HIRIMOTU, BAMBARA, SAMOAN, HUNGARIAN, TAMIL, TURKISH, LITHUANIAN, NORTHERNSAMI, AMHARIC, SANGO, MACEDONIAN, INDONESIAN, ARABIC, NDONGA, JAPANESE, MARATHI, BISLAMA, CORNISH, BIHARI, INUPIAQ, MALTESE, SINHALESE, GUARANI, BELARUSIAN, AVARIC, BENGALI, INUKTITUT, NAURU, BURMESE, HAUSA, UKRAINIAN, SHONA, BOSNIAN, CHUVASH, QUECHUA, EWE, SPANISH, AKAN, YORUBA, GAELIC, ABKHAZIAN, ITALIAN, LATIN, SANSKRIT, KINYARWANDA, GREENLANDIC, ASSAMESE, IGBO, XHOSA, URDU, FIJIAN, SARDINIAN, ROMANSH, CORSICAN, TATAR, AYMARA, TURKMEN, LUBAKATANGA, AVESTAN, KOREAN, OCCITAN, TIBETAN, FAROESE, KANNADA, UNKNOWN, HERERO, ARMENIAN, LUXEMBOURGISH, MONGOLIAN, NORTHNDEBELE, DANISH, NORWEGIAN, GEORGIAN, NAVAJO, KIKUYU, ICELANDIC, RUSSIAN, ESPERANTO, KASHMIRI, GERMAN, IDO, THAI, UZBEK, NORWEGIANBOKMAL, HINDI, AZERBAIJANI, FINNISH, TAGALOG, INTERLINGUA, LINGALA, KURDISH, CHINESE, YIDDISH, NORWEGIANNYNORSK, HAITIAN, GREEK, SLOVENIAN, SERBIAN, TSONGA, TSWANA, OJIBWA, ALBANIAN, CHECHEN, NEPALI, KONGO, CATALAN, CHAMORRO, UIGHUR, MAORI, GUJARATI, PANJABI]
 at [Source: (String)"{"nerTags":[],"metadata":{"tika_metadata_tiff_yresolution":"72.0","tika_metadata_primary_platform":"Apple Computer, Inc.","tika_metadata_signature":"acsp","tika_metadata_content_type":"image/jpeg","tika_metadata_tiff_bitspersample":"8","tika_metadata_blue_trc":"0.0070344","tika_metadata_profile_connection_space":"XYZ","tika_metadata_compression_type":"Baseline","tika_metadata_caption_digest":"212 29 140 217 143 0 178 4 233 128 9 152 236 248 66 126","tika_metadata_tiff_resolutionunit":"Inch","tik"[truncated 4679 chars]; line: 1, column: 3863] (through reference chain: org.icij.datashare.text.Document["language"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1549)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:911)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:255)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:179)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
	at org.icij.datashare.json.JsonObjectMapper.getObject(JsonObjectMapper.java:86)
```

**Comment by bamthomas** [comment]
fixed with release 3.0.3
