### ISSUE TITLE
NullPointerException when creating batch search with sqlite

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#217]
When we use batchsearches with sqlite, there is a NullPointerException coming from the loading and ordering batchsearches with the timestamp.
```
2019-08-05 11:10:56,059 [Worker: RequestDispatcher: Thread-21] ERROR Fluent - Unable to GET /api/batch/search
2019-08-05 11:10:56,061 [Worker: RequestDispatcher: Thread-21] ERROR Fluent - Unexpected error:
java.lang.NullPointerException: null
        at org.icij.datashare.db.JooqBatchSearchRepository.createBatchSearchFrom(JooqBatchSearchRepository.java:139)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:899)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.icij.datashare.db.JooqBatchSearchRepository.get(JooqBatchSearchRepository.java:81)
        at org.icij.datashare.web.BatchSearchResource.getSearches(BatchSearchResource.java:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.codestory.http.routes.ReflectionRoute.invoke(ReflectionRoute.java:83)
        at net.codestory.http.routes.ReflectionRoute.lambda$body$0(ReflectionRoute.java:45)
        at net.codestory.http.annotations.MethodAnnotations.apply(MethodAnnotations.java:48)
        at net.codestory.http.routes.ReflectionRoute.body(ReflectionRoute.java:40)
        at net.codestory.http.routes.RouteWithPattern.body(RouteWithPattern.java:56)
        at net.codestory.http.routes.Route.apply(Route.java:25)
        at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$98caf044$1(RouteCollection.java:577)
        at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
        at org.icij.datashare.web.IndexWaiterFilter.apply(IndexWaiterFilter.java:38)
        at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
        at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
        at org.icij.datashare.mode.CorsFilter.apply(CorsFilter.java:19)
        at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
        at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
        at org.icij.datashare.web.IndexWaiterFilter.apply(IndexWaiterFilter.java:38)
        at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
        at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
        at org.icij.datashare.session.LocalUserFilter.otherUri(LocalUserFilter.java:25)
        at net.codestory.http.filters.auth.CookieAuthFilter.apply(CookieAuthFilter.java:78)
        at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
        at net.codestory.http.routes.RouteCollection.apply(RouteCollection.java:567)
        at net.codestory.http.AbstractWebServer.handleHttp(AbstractWebServer.java:152)
        at net.codestory.http.internal.SimpleServerWrapper.handle(SimpleServerWrapper.java:71)
        at org.simpleframework.http.socket.service.RouterContainer.handle(RouterContainer.java:106)
        at org.simpleframework.http.core.RequestDispatcher.dispatch(RequestDispatcher.java:121)
        at org.simpleframework.http.core.RequestDispatcher.run(RequestDispatcher.java:103)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

The unit test is working fine : it stores the date with a string like `2019-08-02 12:13:14.123` but the app stores it with nb of seconds from 1970 :

```
sqlite> select * from batch_search;
c7b47d5a-a8e9-4c9d-9921-88bcba1ac225|test||local|local-datashare|1565002228020|QUEUED
```

Maybe a class loading order issue ?

**Comment by annelhote** [comment]
Updated and tested in local ! Everything is perfect !
