### ISSUE TITLE
Batch search: BatchSearch creation failed

### ISSUE THREAD

**Issue by annelhote** [ICIJ/datashare#264]
Unable to POST /api/batch/search/<project>

java.lang.IllegalStateException: Duplicate key 0
	at org.icij.datashare.batch.BatchSearch.lambda$toLinkedHashMap$1(BatchSearch.java:86)
	at java.util.HashMap.merge(HashMap.java:1254)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.icij.datashare.batch.BatchSearch.toLinkedHashMap(BatchSearch.java:85)
	at org.icij.datashare.batch.BatchSearch.<init>(BatchSearch.java:44)
	at org.icij.datashare.web.BatchSearchResource.search(BatchSearchResource.java:91)
			4 lines skipped for [sun., java.lang.reflect.Method]
	at net.codestory.http.routes.ReflectionRoute.invoke(ReflectionRoute.java:83)
	at net.codestory.http.routes.ReflectionRoute.lambda$body$0(ReflectionRoute.java:45)
	at net.codestory.http.annotations.MethodAnnotations.apply(MethodAnnotations.java:48)
	at net.codestory.http.routes.ReflectionRoute.body(ReflectionRoute.java:40)
	at net.codestory.http.routes.RouteWithPattern.body(RouteWithPattern.java:56)
	at net.codestory.http.routes.Route.apply(Route.java:25)
	at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$98caf044$1(RouteCollection.java:577)
	at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
	at net.codestory.http.filters.auth.CookieAuthFilter.otherUri(CookieAuthFilter.java:103)
	at net.codestory.http.filters.auth.CookieAuthFilter.apply(CookieAuthFilter.java:78)
	at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
	at net.codestory.http.routes.RouteCollection.apply(RouteCollection.java:567)
	at net.codestory.http.AbstractWebServer.handleHttp(AbstractWebServer.java:152)
	at net.codestory.http.internal.SimpleServerWrapper.handle(SimpleServerWrapper.java:71)
	at org.simpleframework.http.socket.service.RouterContainer.handle(RouterContainer.java:106)
	at org.simpleframework.http.core.RequestDispatcher.dispatch(RequestDispatcher.java:121)
	at org.simpleframework.http.core.RequestDispatcher.run(RequestDispatcher.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by annelhote** [comment]
I deleted all the batchSearches linked to Soliine.
