### ISSUE TITLE
Multithreading with Jedis : JedisDataException

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#3]
When running datashare with a multithreaded env, we see :

    2018-05-19 11:03:02,115 [pool-5-thread-1] ERROR DocumentConsumer - Exception while consuming file:  "/home/datashare/data/apollo-global-management-2009-tax-ruling.pdf".
    redis.clients.jedis.exceptions.JedisDataException: ERR Protocol error: expected '$', got ' '
	at redis.clients.jedis.Protocol.processError(Protocol.java:127)
	at redis.clients.jedis.Protocol.process(Protocol.java:161)
	at redis.clients.jedis.Protocol.read(Protocol.java:215)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340)
	at redis.clients.jedis.Connection.getIntegerReply(Connection.java:265)
	at redis.clients.jedis.Jedis.publish(Jedis.java:2690)
	at org.icij.datashare.com.redis.RedisPublisher.publish(RedisPublisher.java:22)
	at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchSpewer.indexDocument(ElasticsearchSpewer.java:133)
	at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchSpewer.write(ElasticsearchSpewer.java:66)
	at org.icij.extract.extractor.Extractor.extract(Extractor.java:272)
	at org.icij.extract.extractor.DocumentConsumer.lambda$accept$0(DocumentConsumer.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

This is probably caused by : https://github.com/xetorthio/jedis/issues/1358

**Comment by bamthomas** [comment]
tested on the Julian computer
