### ISSUE TITLE
[windows] Installer without docker

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#360]
Install datashare without docker : 

- install java if not present
- install tesseract if not present

**Comment by bamthomas** [comment]
see #317

**Comment by bamthomas** [comment]
the build with one jar is breaking embedded mode (probably a conflict on lucene libs) :

```
Exception in thread "elasticsearch[GCJRx-u][search][T#1]" java.lang.NoSuchFieldError: CONSTANT_SCORE_AUTO_REWRITE_DEFAULT
        at org.apache.lucene.queryparser.classic.QueryParserBase.<init>(QueryParserBase.java:69)
        at org.apache.lucene.queryparser.classic.QueryParser.<init>(QueryParser.java:532)
        at org.apache.lucene.queryparser.classic.QueryParser.<init>(QueryParser.java:102)
        at org.apache.lucene.queryparser.classic.XQueryParser.<init>(XQueryParser.java:33)
        at org.elasticsearch.index.search.QueryStringQueryParser.<init>(QueryStringQueryParser.java:149)
        at org.elasticsearch.index.search.QueryStringQueryParser.<init>(QueryStringQueryParser.java:141)
        at org.elasticsearch.index.query.QueryStringQueryBuilder.doToQuery(QueryStringQueryBuilder.java:977)
        at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:104)
        at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:404)

```

**Comment by Soliine** [comment]
- add a pop in to ask if user wants to unsintall the old version
- test on Windows 7Th 
- update User Guide > Bruno sent screenshots
