### ISSUE TITLE
Backend should be able to inject plugins assets to the frontend

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#375]
Datashare backend should received a new argument to point to a plugins directory (`--pluginsDir`). 

In this directory, users are able to copy a plugin's directory. A plugin is a Node-compatible module. As described in [NPM documentation](https://docs.npmjs.com/about-packages-and-modules#about-modules), it can be:

```
* A folder with a package.json file containing a "main" field.
* A folder with an index.js file in it.
```

This way we can rely on NPM/Yarn to handle built packages.

Datashare will read the content of each module in the `plugins` directory to automatically inject them in the client's `index.html`. The backend will then have to serve the plugin files exclusivly to the client. The entrypoint of each plugin (usualy the `main` property of [package.json](https://docs.npmjs.com/files/package.json)) will be injected with a `<script>` tag, right before the closing `</body>` tag.

It doesn't look like [this has been standardized yet](https://jaketrent.com/post/package-json-style-attribute/), but it's more and more frequent that package.json files expose an extra "style" property. Datashare should also be able to read this in order to inject the stylesheet before the `</head>` tag.

User shouldn't have to restart Datashare to install a plugin. This way we'll be able to ease plugins development and dynamically import them in the future.

**Comment by pirhoo** [comment]
Datashare doesn't seems to read package.json:

```bash
# Download a plugin from NPM
npm pack @icij/datashare-plugin-site-alert
# Untar the plugin's package
tar zxvf icij-datashare-plugin-site-alert-*.tgz
```

When reloading, Datashare throw an exception:

```
2020-02-19 12:25:49,778 [Worker: RequestDispatcher: Thread-8] ERROR Fluent - Unable to GET /
2020-02-19 12:25:49,780 [Worker: RequestDispatcher: Thread-8] ERROR Fluent - Unexpected error:
java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of STAR
T_OBJECT token
 at [Source: (File); line: 6, column: 22] (through reference chain: java.util.HashMap["dependencies"])
        at org.icij.datashare.PluginService.getPluginProperty(PluginService.java:75)
        at org.icij.datashare.PluginService.getPluginUrl(PluginService.java:41)
        at org.icij.datashare.PluginService.lambda$addPlugins$1(PluginService.java:28)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)

        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)                                                     [392/2187]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.icij.datashare.PluginService.addPlugins(PluginService.java:29)
        at org.icij.datashare.web.RootResource.getRoot(RootResource.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.codestory.http.routes.ReflectionRoute.invoke(ReflectionRoute.java:83)
        at net.codestory.http.routes.ReflectionRoute.lambda$body$0(ReflectionRoute.java:45)
        at net.codestory.http.annotations.MethodAnnotations.apply(MethodAnnotations.java:48)
        at net.codestory.http.routes.ReflectionRoute.body(ReflectionRoute.java:40)
        at net.codestory.http.routes.RouteWithPattern.body(RouteWithPattern.java:56)
        at net.codestory.http.routes.Route.apply(Route.java:25)
        at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$98caf044$1(RouteCollection.java:577)
        at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
        at org.icij.datashare.web.IndexWaiterFilter.apply(IndexWaiterFilter.java:41)
        at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
        at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
        at org.icij.datashare.web.IndexWaiterFilter.apply(IndexWaiterFilter.java:41)
        at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
        at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
        at org.icij.datashare.session.LocalUserFilter.otherUri(LocalUserFilter.java:30)
        at net.codestory.http.filters.auth.CookieAuthFilter.apply(CookieAuthFilter.java:78)
        at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
        at net.codestory.http.routes.RouteCollection.apply(RouteCollection.java:567)
        at net.codestory.http.AbstractWebServer.handleHttp(AbstractWebServer.java:152)
        at net.codestory.http.internal.SimpleServerWrapper.handle(SimpleServerWrapper.java:71)
        at org.simpleframework.http.socket.service.RouterContainer.handle(RouterContainer.java:106)
        at org.simpleframework.http.core.RequestDispatcher.dispatch(RequestDispatcher.java:121)
        at org.simpleframework.http.core.RequestDispatcher.run(RequestDispatcher.java:103)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: (File); line: 6, column: 22] (through reference chain: java.util.HashMap["dependencies"])
```

It looks like other properties than `main` in package.json are creating this error. 

If I simplify the package.json to:

```json
{
  "main": "dist/index.umd.min.js"
}
```

Then the page load normally but `dist/index.umd.min.js` is not injected.

**Comment by pirhoo** [comment]
Scripts injected with a package.json see their root path trimmed.

Example `hello-world/package.json`:

```json
{
  "main": "dist/index.js"
}
```

Is injected as 

```html
<script src="/dist/index.js"></script>
```

Instead of:

```html
<script src="/hello-world/dist/index.js"></script>
```

**Comment by pirhoo** [comment]
Hey @bamthomas, did you also implemented the stylesheet injection? As described in my initial issue:

> [...] it's more and more frequent that package.json files expose an extra "style" property. Datashare should also be able to read this in order to inject the stylesheet before the </head> tag.

**Comment by bamthomas** [comment]
yes see https://github.com/ICIJ/datashare/commit/2cdbf697dbd7ca90fa9eba651966b56676b05bb3

**Comment by pirhoo** [comment]
Perfect, thanks!
