### ISSUE TITLE
Indexing is not working at the first try

### ISSUE THREAD

**Issue by annelhote** [ICIJ/datashare#455]
On my local installation of Datashare running in devenv, last version of back and last version of front. Same problem with and without embedded front.

To reproduce :
- Open your dataDir `/home/dev/data` and put a file `file_01.txt` in it
- Run Datashare with your dataDir set to `/home/dev/data`
- Index your files **without** skipping the already indexed files and check that everything is OK
- Delete all your indexed files from Datashare with the Trash icon (bottom left)
- In your dataDir `/home/dev/data`, remove your file `file_01.txt` and add another file `file_02.txt` in it
- Index your files **without** skipping the already indexed files
=> You got an error and the previous file `file_01.txt` is indexed
- Index your files **without** skipping the already indexed files
=> Now it works and only your file `file_02.txt` should be indexed

**Comment by annelhote** [comment]
Logs of the first indexing, FAIL one:

```
2020-04-29 15:01:30,733 [redisson-netty-8-5] INFO  MasterConnectionPool - 1 connections initialized for redis/172.18.0.3:6379
2020-04-29 15:01:30,734 [redisson-netty-8-6] INFO  MasterPubSubConnectionPool - 1 connections initialized for redis/172.18.0.3:6379
2020-04-29 15:01:30,748 [pool-2-thread-3] INFO  Scanner - Queuing scan of: "/home/dev/data".
2020-04-29 15:01:30,748 [pool-2-thread-3] INFO  ScannerVisitor - Starting scan of: "/home/dev/data".
2020-04-29 15:01:30,749 [pool-2-thread-3] INFO  ScannerVisitor - Entering directory: "/home/dev/data".
2020-04-29 15:01:30,778 [pool-2-thread-3] INFO  ScannerVisitor - Completed scan of: "/home/dev/data".
2020-04-29 15:01:31,566 [Worker: RequestDispatcher: Thread-12] INFO  ElasticsearchSpewer - spewer defined with cfg{indexType='doc', indexJoinField='join', docTypeField='type', shards=1, replicas=1}
2020-04-29 15:01:31,599 [redisson-netty-11-5] INFO  MasterConnectionPool - 1 connections initialized for redis/172.18.0.3:6379
2020-04-29 15:01:31,599 [redisson-netty-11-6] INFO  MasterPubSubConnectionPool - 1 connections initialized for redis/172.18.0.3:6379
2020-04-29 15:01:31,623 [Worker: RequestDispatcher: Thread-12] INFO  IndexTask - {tcpListenPort=8080, stages=SCAN,INDEX,NLP, scrollSize=1000, backHost=http://localhost:8888, elasticsearchAddress=http://elasticsearch:9200, frontHost
=http://localhost:, queueName=extract:queue, browserOpenLink=false, sessionTtlSeconds=43200, scrollSlices=1, queueType=redis, filterSet=extract:filter, filter=false, protectedUriPrefix=/api/, cors=*, oauthApiUrl=http://xemx:3001/ap
i/v1/me.json, mode=LOCAL, redisPoolSize=1, oauthAuthorizeUrl=http://xemx:3001/oauth/authorize, redisAddress=redis://redis:6379, defaultUserName=local, ocr=true, nlpParallelism=1, parserParallelism=1, dataSourceUrl=jdbc:postgresql:/
/postgresql/datashare?user=test&password=test, defaultProject=local-datashare, elasticsearchDataPath=/home/datashare/es, dataDir=/home/dev/data, pluginsDir=/home/dev/plugins, oauthTokenUrl=http://xemx:3001/oauth/token, busType=redi
s, clusterName=datashare, previewHost=http://localhost:5000, messageBusAddress=redis, parallelism=8}
2020-04-29 15:01:31,623 [pool-2-thread-4] INFO  IndexTask - Processing up to 8 file(s) in parallel
2020-04-29 15:01:31,624 [pool-9-thread-1] INFO  DocumentQueueDrainer - Draining to consumer until stopped or interrupted.
2020-04-29 15:01:31,626 [pool-9-thread-1] INFO  DocumentConsumer - Sending to thread pool; will queue if full: "/home/dev/data/phonenumbers_fr_12.txt".
2020-04-29 15:01:31,626 [pool-8-thread-1] INFO  DocumentConsumer - Beginning extraction: "/home/dev/data/phonenumbers_fr_12.txt".
2020-04-29 15:01:31,628 [pool-9-thread-1] INFO  DocumentConsumer - Sending to thread pool; will queue if full: "/home/dev/data/phonenumbers_fr_05.txt".
2020-04-29 15:01:31,631 [pool-8-thread-2] INFO  DocumentConsumer - Beginning extraction: "/home/dev/data/phonenumbers_fr_05.txt".
2020-04-29 15:01:31,634 [pool-9-thread-1] INFO  DocumentConsumer - Sending to thread pool; will queue if full: "/home/dev/data/phonenumbers_fr_01.txt".
2020-04-29 15:01:31,634 [pool-8-thread-1] INFO  Extractor - /home/dev/data/phonenumbers_fr_12.txt extracted in 8ms
2020-04-29 15:01:31,635 [pool-8-thread-2] ERROR DocumentConsumer - Exception while consuming file: "/home/dev/data/phonenumbers_fr_05.txt".
java.nio.file.NoSuchFileException: /home/dev/data/phonenumbers_fr_05.txt
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
        at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
        at java.nio.file.Files.readAttributes(Files.java:1737)
        at java.nio.file.Files.size(Files.java:2332)
        at org.apache.tika.io.TikaInputStream.get(TikaInputStream.java:226)
        at org.icij.extract.extractor.Extractor.extract(Extractor.java:381)
        at org.icij.extract.extractor.Extractor.extract(Extractor.java:264)
        at org.icij.extract.extractor.DocumentConsumer.lambda$accept$0(DocumentConsumer.java:126)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-04-29 15:01:31,637 [pool-8-thread-3] INFO  DocumentConsumer - Beginning extraction: "/home/dev/data/phonenumbers_fr_01.txt".
2020-04-29 15:01:31,637 [pool-9-thread-1] INFO  DocumentQueueDrainer - Continuous draining stopped.
2020-04-29 15:01:31,637 [pool-2-thread-4] INFO  DocumentQueueDrainer - Shutting down.
2020-04-29 15:01:31,638 [pool-2-thread-4] INFO  DocumentQueueDrainer - Awaiting completion up to 10 SECONDS.
2020-04-29 15:01:31,638 [pool-2-thread-4] INFO  DocumentQueueDrainer - Terminated.
2020-04-29 15:01:31,638 [pool-2-thread-4] INFO  IndexTask - drained 3 documents. Waiting for consumer to shutdown
2020-04-29 15:01:31,640 [pool-2-thread-4] INFO  DocumentConsumer - Shutting down.
2020-04-29 15:01:31,640 [pool-2-thread-4] INFO  DocumentConsumer - Awaiting completion up to 30 MINUTES.
2020-04-29 15:01:31,649 [pool-8-thread-3] INFO  Extractor - /home/dev/data/phonenumbers_fr_01.txt extracted in 12ms
2020-04-29 15:01:31,652 [pool-8-thread-1] INFO  ElasticsearchSpewer - Document cb23...a458 added to elasticsearch in 12ms: /home/dev/data/phonenumbers_fr_12.txt
2020-04-29 15:01:31,662 [pool-8-thread-3] INFO  ElasticsearchSpewer - Document d0e2...ba93 added to elasticsearch in 9ms: /home/dev/data/phonenumbers_fr_01.txt
2020-04-29 15:01:31,663 [pool-2-thread-4] INFO  DocumentConsumer - Terminated.
2020-04-29 15:01:31,716 [pool-2-thread-4] INFO  IndexTask - exiting
```

**Comment by annelhote** [comment]
Logs of the second indexing, SUCCESS one :

```
2020-04-29 15:05:11,497 [redisson-netty-14-5] INFO  MasterConnectionPool - 1 connections initialized for redis/172.18.0.3:6379
2020-04-29 15:05:11,499 [redisson-netty-14-6] INFO  MasterPubSubConnectionPool - 1 connections initialized for redis/172.18.0.3:6379
2020-04-29 15:05:11,512 [pool-2-thread-5] INFO  Scanner - Queuing scan of: "/home/dev/data".
2020-04-29 15:05:11,512 [pool-2-thread-5] INFO  ScannerVisitor - Starting scan of: "/home/dev/data".
2020-04-29 15:05:11,513 [pool-2-thread-5] INFO  ScannerVisitor - Entering directory: "/home/dev/data".
2020-04-29 15:05:11,532 [pool-2-thread-5] INFO  ScannerVisitor - Completed scan of: "/home/dev/data".
2020-04-29 15:05:12,084 [Worker: RequestDispatcher: Thread-31] INFO  ElasticsearchSpewer - spewer defined with cfg{indexType='doc', indexJoinField='join', docTypeField='type', shards=1, replicas=1}
2020-04-29 15:05:12,116 [redisson-netty-17-5] INFO  MasterConnectionPool - 1 connections initialized for redis/172.18.0.3:6379
2020-04-29 15:05:12,117 [redisson-netty-17-6] INFO  MasterPubSubConnectionPool - 1 connections initialized for redis/172.18.0.3:6379
2020-04-29 15:05:12,131 [Worker: RequestDispatcher: Thread-31] INFO  IndexTask - {tcpListenPort=8080, stages=SCAN,INDEX,NLP, scrollSize=1000, backHost=http://localhost:8888, elasticsearchAddress=http://elasticsearch:9200, frontHost
=http://localhost:, queueName=extract:queue, browserOpenLink=false, sessionTtlSeconds=43200, scrollSlices=1, queueType=redis, filterSet=extract:filter, filter=false, protectedUriPrefix=/api/, cors=*, oauthApiUrl=http://xemx:3001/ap
i/v1/me.json, mode=LOCAL, redisPoolSize=1, oauthAuthorizeUrl=http://xemx:3001/oauth/authorize, redisAddress=redis://redis:6379, defaultUserName=local, ocr=true, nlpParallelism=1, parserParallelism=1, dataSourceUrl=jdbc:postgresql:/
/postgresql/datashare?user=test&password=test, defaultProject=local-datashare, elasticsearchDataPath=/home/datashare/es, dataDir=/home/dev/data, pluginsDir=/home/dev/plugins, oauthTokenUrl=http://xemx:3001/oauth/token, busType=redi
s, clusterName=datashare, previewHost=http://localhost:5000, messageBusAddress=redis, parallelism=8}
2020-04-29 15:05:12,131 [pool-2-thread-6] INFO  IndexTask - Processing up to 8 file(s) in parallel
2020-04-29 15:05:12,132 [pool-12-thread-1] INFO  DocumentQueueDrainer - Draining to consumer until stopped or interrupted.
2020-04-29 15:05:12,134 [pool-12-thread-1] INFO  DocumentConsumer - Sending to thread pool; will queue if full: "/home/dev/data/phonenumbers_fr_12.txt".
2020-04-29 15:05:12,135 [pool-11-thread-1] INFO  DocumentConsumer - Beginning extraction: "/home/dev/data/phonenumbers_fr_12.txt".
2020-04-29 15:05:12,138 [pool-12-thread-1] INFO  DocumentConsumer - Sending to thread pool; will queue if full: "/home/dev/data/phonenumbers_fr_10.txt".
2020-04-29 15:05:12,141 [pool-11-thread-1] INFO  Extractor - /home/dev/data/phonenumbers_fr_12.txt extracted in 6ms
2020-04-29 15:05:12,141 [pool-11-thread-2] INFO  DocumentConsumer - Beginning extraction: "/home/dev/data/phonenumbers_fr_10.txt".
2020-04-29 15:05:12,151 [pool-12-thread-1] INFO  DocumentConsumer - Sending to thread pool; will queue if full: "/home/dev/data/phonenumbers_fr_01.txt".
2020-04-29 15:05:12,152 [pool-11-thread-2] INFO  Extractor - /home/dev/data/phonenumbers_fr_10.txt extracted in 11ms
2020-04-29 15:05:12,160 [pool-11-thread-3] INFO  DocumentConsumer - Beginning extraction: "/home/dev/data/phonenumbers_fr_01.txt".
2020-04-29 15:05:12,161 [pool-12-thread-1] INFO  DocumentQueueDrainer - Continuous draining stopped.
2020-04-29 15:05:12,166 [pool-2-thread-6] INFO  DocumentQueueDrainer - Shutting down.
2020-04-29 15:05:12,167 [pool-2-thread-6] INFO  DocumentQueueDrainer - Awaiting completion up to 10 SECONDS.
2020-04-29 15:05:12,167 [pool-2-thread-6] INFO  DocumentQueueDrainer - Terminated.
2020-04-29 15:05:12,168 [pool-2-thread-6] INFO  IndexTask - drained 3 documents. Waiting for consumer to shutdown
2020-04-29 15:05:12,170 [pool-11-thread-3] INFO  Extractor - /home/dev/data/phonenumbers_fr_01.txt extracted in 9ms
2020-04-29 15:05:12,171 [pool-2-thread-6] INFO  DocumentConsumer - Shutting down.
2020-04-29 15:05:12,171 [pool-2-thread-6] INFO  DocumentConsumer - Awaiting completion up to 30 MINUTES.
2020-04-29 15:05:12,173 [pool-11-thread-1] INFO  ElasticsearchSpewer - Document cb23...a458 added to elasticsearch in 12ms: /home/dev/data/phonenumbers_fr_12.txt
2020-04-29 15:05:12,180 [pool-11-thread-2] INFO  ElasticsearchSpewer - Document 8ed5...5518 added to elasticsearch in 18ms: /home/dev/data/phonenumbers_fr_10.txt
2020-04-29 15:05:12,183 [pool-11-thread-3] INFO  ElasticsearchSpewer - Document d0e2...ba93 added to elasticsearch in 9ms: /home/dev/data/phonenumbers_fr_01.txt
2020-04-29 15:05:12,183 [pool-2-thread-6] INFO  DocumentConsumer - Terminated.
2020-04-29 15:05:12,196 [pool-2-thread-6] INFO  IndexTask - exiting
```

**Comment by annelhote** [comment]
It is not the case anymore.
