### ISSUE TITLE
Batch search error: "listener timeout after waiting for [30000] ms'"

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#462]
We saw this error message in several batch searches. We manage to reproduce with batch searches either with lots of queries or on large project.

**Comment by Soliine** [comment]
To use an example, please find the result at date "April 2, 2020 2:20 PM" called "French PM (including previous)" in our server Datashare. 
I used this .csv if you need for future tests: 
[French parliament members - Sheet3.csv.zip](https://github.com/ICIJ/datashare/files/4644573/French.parliament.members.-.Sheet3.csv.zip)

**Comment by bamthomas** [comment]
I've reproduced the issue on my computer pointing to ES/prod  

```
2020-06-05 14:03:47,235 [main] INFO  HikariDataSource - HikariPool-2 - Shutdown completed.
2020-06-05 14:03:47,399 [main] INFO  Indexer - indexer defined with cfg{indexType='doc', indexJoinField='join', docTypeField='type', shards=1, replicas=1}
2020-06-05 14:03:48,000 [main] INFO  BatchSearchRunner - found 1 queued batch searches
2020-06-05 14:03:48,000 [main] INFO  BatchSearchRunner - running 9 queries for batch search f29de024-b43f-49eb-a330-bacb97dbca0b on project Project{name='xxxxxx'} with throttle 0ms


2020-06-05 14:05:41,786 [main] ERROR BatchSearchRunner - error when running batch f29de024-b43f-49eb-a330-bacb97dbca0b
java.io.IOException: listener timeout after waiting for [30000] ms
        at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:905)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:229)
        at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1593)
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1563)
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1546)
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1512)

```

**Comment by bamthomas** [comment]
may be related to [this SO thread](https://stackoverflow.com/questions/51341806/elasticsearch-resthighlevelclient-listener-timeout-after-waiting-for-30000)

**Comment by bamthomas** [comment]
for the delay problem and periodicity of crontab we created the issue #537
