### ISSUE TITLE
ERROR CoreNlpNerModels - failed loading NER

### ISSUE THREAD

**Issue by nodearcnode** [ICIJ/datashare#587]
**Describe the bug**
Find people with CoreNLP fails with error: `ERROR CoreNlpNerModels - failed loading NER`

**Desktop:**
 - OS: Windows 10 home
 - Browser: Chrome

**To Reproduce**
1. https://icij.gitbook.io/datashare/windows/install-datashare-on-windows
2. Install 7.5.2 with installDatashareStandalone.exe
3. Paste docs in de datadir and then go to 'Analyse' 
4. Click on 'Extract text' 
--- **(untill here everything works as expected)** ---
5. Click on 'Find people ...' / use CoreNLP
6. See error: 

2020-08-11 14:28:54,761 [Worker: RequestDispatcher: Thread-27] INFO  AbstractModels - synchronize models is set to true
2020-08-11 14:28:54,765 [Worker: RequestDispatcher: Thread-27] INFO  TaskResource - waiting for NlpApp org.icij.datashare.text.nlp.corenlp.CorenlpPipeline@46c30cc8 to listen...
2020-08-11 14:28:54,765 [pool-2-thread-1] INFO  NlpApp - running NlpApp for CORENLP pipeline with 1 thread(s)
2020-08-11 14:28:54,771 [Worker: RequestDispatcher: Thread-27] INFO  TaskResource - ...org.icij.datashare.text.nlp.corenlp.CorenlpPipeline@46c30cc8 is listening
2020-08-11 14:28:54,774 [pool-2-thread-2] INFO  ResumeNlpTask - resuming NLP name finding for index local-datashare and [CORENLP]
2020-08-11 14:28:54,886 [pool-2-thread-2] INFO  ResumeNlpTask - sent EXTRACT_NLP message for 6 files without [CORENLP] pipeline tags
2020-08-11 14:28:54,892 [CORENLP-0] INFO  NlpConsumer - extracting CORENLP entities for document 2e267fa5db6be41d1a2b140c6d52ec0315ac53af68005910b9a19e4aa6e8b5eb69183cf3105135e40b7dd59b1d8dd893
2020-08-11 14:28:54,895 [pool-2-thread-1] INFO  MemoryDataBus - exiting org.icij.datashare.nlp.NlpForwarder$$Lambda$2404/509581138@60b15840
2020-08-11 14:28:54,895 [pool-2-thread-1] INFO  NlpApp - forwarder exited waiting for consumer(s) to finish
2020-08-11 14:28:54,896 [CORENLP-0] INFO  CorenlpPipeline - initializing CORENLP Skipping... Stage unsupported for DUTCH [TOKEN, SENTENCE, POS, LEMMA, NER]
2020-08-11 14:28:54,907 [CORENLP-0] INFO  NlpConsumer - extracting CORENLP entities for document 7da394588f31dd97a4342727f323d3c2a2dd8aabe8fce6f0896005f1384e7868f8b1c8acbbbe7c5183e0a1301240bfd5
2020-08-11 14:28:54,908 [CORENLP-0] INFO  CorenlpPipeline - initializing CORENLP ENGLISH [TOKEN, SENTENCE, POS, LEMMA, NER]
2020-08-11 14:28:55,994 [CORENLP-0] INFO  CoreNlpNerModels - adding models\corenlp\4-0-0\en\stanford-corenlp-4.0.0-models-en.jar to system classloader
2020-08-11 14:28:56,079 [CORENLP-0] **ERROR CoreNlpNerModels - failed loading NER**
java.io.IOException: Unable to open "edu\stanford\nlp\models\ner\english.all.3class.caseless.distsim.crf.ser.gz" as class path, filename or URL
        at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:481)
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1505)
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1497)
        at edu.stanford.nlp.ie.crf.CRFClassifier.getClassifier(CRFClassifier.java:2888)
        at org.icij.datashare.text.nlp.corenlp.models.CoreNlpNerModels.loadModelFile(CoreNlpNerModels.java:75)
        at org.icij.datashare.text.nlp.corenlp.models.CoreNlpNerModels.loadModelFile(CoreNlpNerModels.java:39)
        at org.icij.datashare.text.nlp.AbstractModels.load(AbstractModels.java:59)
        at org.icij.datashare.text.nlp.AbstractModels.get(AbstractModels.java:46)
        at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.initializeNerAnnotator(CorenlpPipeline.java:179)
        at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.initialize(CorenlpPipeline.java:79)
        at org.icij.datashare.nlp.NlpConsumer.findNamedEntities(NlpConsumer.java:72)
        at org.icij.datashare.nlp.NlpConsumer.call(NlpConsumer.java:43)
        at org.icij.datashare.nlp.NlpConsumer.call(NlpConsumer.java:20)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-08-11 14:28:56,083 [CORENLP-0] INFO  CorenlpPipeline - name-finding for ENGLISH
2020-08-11 14:28:56,590 [CORENLP-0] INFO  CoreNlpNerModels - adding models\corenlp\4-0-0\en\stanford-corenlp-4.0.0-models-en.jar to system classloader
2020-08-11 14:28:56,591 [CORENLP-0] ERROR CoreNlpNerModels - failed loading NER
java.io.IOException: Unable to open "edu\stanford\nlp\models\ner\english.all.3class.caseless.distsim.crf.ser.gz" as class path, filename or URL
        at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:481)
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1505)
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1497)
        at edu.stanford.nlp.ie.crf.CRFClassifier.getClassifier(CRFClassifier.java:2888)
        at org.icij.datashare.text.nlp.corenlp.models.CoreNlpNerModels.loadModelFile(CoreNlpNerModels.java:75)
        at org.icij.datashare.text.nlp.corenlp.models.CoreNlpNerModels.loadModelFile(CoreNlpNerModels.java:39)
        at org.icij.datashare.text.nlp.AbstractModels.load(AbstractModels.java:59)
        at org.icij.datashare.text.nlp.AbstractModels.get(AbstractModels.java:46)
        at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.processNerClassifier(CorenlpPipeline.java:196)
        at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.process(CorenlpPipeline.java:91)
        at org.icij.datashare.nlp.NlpConsumer.findNamedEntities(NlpConsumer.java:73)
        at org.icij.datashare.nlp.NlpConsumer.call(NlpConsumer.java:43)
        at org.icij.datashare.nlp.NlpConsumer.call(NlpConsumer.java:20)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-08-11 14:28:56,595 [CORENLP-0] WARN  NlpConsumer - error in consumer main loop

**Comment by Soliine** [comment]
Hello, thanks for reporting this. Datashare's backend developers are off in the next weeks. They will get back to you as soon as possible. Your ticket was put in our backlog. Thanks.

**Comment by Soliine** [comment]
Hello @nodearcnode, we made some progress here. Can you please install the latest version of Datashare, try again and tell us if it works now?

**Comment by nodearcnode** [comment]
Hi @Soliine ,

Thanks for the update and the effort. I installed 7.7.3 yesterday and have documents in Dutch (which I know of that they can't be parsed) and English, below the logging, some things succeed, but also some errors:




2020-08-31 15:10:47,983 [Worker: RequestDispatcher: Thread-31] INFO  AbstractModels - synchronize models is set to true
2020-08-31 15:10:47,988 [Worker: RequestDispatcher: Thread-31] INFO  TaskResource - waiting for NlpApp org.icij.datashare.text.nlp.corenlp.CorenlpPipeline@4fba5ba4 to listen...
2020-08-31 15:10:47,989 [pool-2-thread-1] INFO  NlpApp - running NlpApp for CORENLP pipeline with 1 thread(s)
2020-08-31 15:10:48,007 [Worker: RequestDispatcher: Thread-31] INFO  TaskResource - ...org.icij.datashare.text.nlp.corenlp.CorenlpPipeline@4fba5ba4 is listening
2020-08-31 15:10:48,010 [pool-2-thread-2] INFO  ResumeNlpTask - resuming NLP name finding for index local-datashare and [CORENLP]
2020-08-31 15:10:48,142 [pool-2-thread-2] INFO  ResumeNlpTask - sent EXTRACT_NLP message for 22 files without [CORENLP] pipeline tags
2020-08-31 15:10:48,156 [pool-2-thread-1] INFO  MemoryDataBus - exiting org.icij.datashare.nlp.NlpForwarder$$Lambda$2473/429710286@71c8db8a
2020-08-31 15:10:48,157 [CORENLP-0] INFO  NlpConsumer - extracting CORENLP entities for document 29ade7e6242b3b865355fb8b8020edc3a2d9f4f1899efc15fb6cf12ae8949a0ca2cca0ae3d7fb24fba1e7ec6cd06d954
2020-08-31 15:10:48,157 [pool-2-thread-1] INFO  NlpApp - forwarder exited waiting for consumer(s) to finish
2020-08-31 15:10:48,161 [CORENLP-0] INFO  CorenlpPipeline - initializing CORENLP Skipping... Stage unsupported for DUTCH [TOKEN, SENTENCE, POS, LEMMA, NER]
2020-08-31 15:10:48,210 [CORENLP-0] INFO  NlpConsumer - extracting CORENLP entities for document cc376c435fec371ae400bc42d0ad0abba4919c4ca550c492ea8367a6f7d0bfb8e53a991df61725eef7c9d5388d45bb87
2020-08-31 15:10:48,211 [CORENLP-0] INFO  CorenlpPipeline - initializing CORENLP Skipping... Stage unsupported for DUTCH [TOKEN, SENTENCE, POS, LEMMA, NER]
2020-08-31 15:10:48,250 [CORENLP-0] INFO  NlpConsumer - extracting CORENLP entities for document 7c3dd361453636aad7e27ccbfd5f25686ac7112c43b9ca08da280cd19c81e1b6ab641ae4d40ee9267ef3ba4b3665b7a5
2020-08-31 15:10:48,251 [CORENLP-0] INFO  CorenlpPipeline - initializing CORENLP Skipping... Stage unsupported for DUTCH [TOKEN, SENTENCE, POS, LEMMA, NER]
2020-08-31 15:10:48,284 [CORENLP-0] INFO  NlpConsumer - extracting CORENLP entities for document d28fecefd7e30e70de7b9a0baf469e39c172025da8dfdcd7ca26bf4dca260537ef3a476781bfb1eea6eb2ab11f366d59
2020-08-31 15:10:48,285 [CORENLP-0] INFO  CorenlpPipeline - initializing CORENLP Skipping... Stage unsupported for DUTCH [TOKEN, SENTENCE, POS, LEMMA, NER]
2020-08-31 15:10:48,312 [CORENLP-0] INFO  NlpConsumer - extracting CORENLP entities for document d92078878d74da1500ee3ccaabdb32c157a3cd354dc4f970ee1042d4b7bbf1bb495d3069f7629a111cdafa4887ace6cd
2020-08-31 15:10:48,313 [CORENLP-0] INFO  CorenlpPipeline - initializing CORENLP Skipping... Stage unsupported for DUTCH [TOKEN, SENTENCE, POS, LEMMA, NER]
2020-08-31 15:10:48,353 [CORENLP-0] INFO  NlpConsumer - extracting CORENLP entities for document eac840c463ecf556dd23176ef8b63b2ced6708a96ad24627098f5ecde56aba5b4f98d0f719877e6b3844a74e7a99a97f
2020-08-31 15:10:48,353 [CORENLP-0] INFO  CorenlpPipeline - initializing CORENLP Skipping... Stage unsupported for DUTCH [TOKEN, SENTENCE, POS, LEMMA, NER]
2020-08-31 15:10:48,384 [CORENLP-0] INFO  NlpConsumer - extracting CORENLP entities for document 2e267fa5db6be41d1a2b140c6d52ec0315ac53af68005910b9a19e4aa6e8b5eb69183cf3105135e40b7dd59b1d8dd893
2020-08-31 15:10:48,385 [CORENLP-0] INFO  CorenlpPipeline - initializing CORENLP Skipping... Stage unsupported for DUTCH [TOKEN, SENTENCE, POS, LEMMA, NER]
2020-08-31 15:10:48,418 [CORENLP-0] INFO  NlpConsumer - extracting CORENLP entities for document 6cd630dce3a2be05fe2f35afdc762d4224ecbdfca3233ccf23473e4299ae31c0c91990d0ad96f73d2c578fae79324f46
2020-08-31 15:10:48,420 [CORENLP-0] INFO  CorenlpPipeline - initializing CORENLP Skipping... Stage unsupported for DUTCH [TOKEN, SENTENCE, POS, LEMMA, NER]
2020-08-31 15:10:48,450 [CORENLP-0] INFO  NlpConsumer - extracting CORENLP entities for document 10e060f408dfee6d0aed8cea5e72ff67c974f7eb49b452b8920c17952a6ba7f5c6379771fa354cf0ede339b7e785b821
2020-08-31 15:10:48,451 [CORENLP-0] INFO  CorenlpPipeline - initializing CORENLP Skipping... Stage unsupported for DUTCH [TOKEN, SENTENCE, POS, LEMMA, NER]
2020-08-31 15:10:48,482 [CORENLP-0] INFO  NlpConsumer - extracting CORENLP entities for document 7129832bb6651492b91b59534238c69230bfa97088977cde427c4542c331e030379eecf0a3e71edbc0c2a559237dc9eb
2020-08-31 15:10:48,482 [CORENLP-0] INFO  CorenlpPipeline - initializing CORENLP Skipping... Stage unsupported for DUTCH [TOKEN, SENTENCE, POS, LEMMA, NER]
2020-08-31 15:10:48,568 [CORENLP-0] INFO  NlpConsumer - extracting CORENLP entities for document 51a245b146e57fe5180a450ee7616f0332470707fa3c1b3732f624e7c6b22bf6ec98fa8f5dd4a705641cc3ecccf1e534
2020-08-31 15:10:48,569 [CORENLP-0] INFO  CorenlpPipeline - initializing CORENLP Skipping... Stage unsupported for DUTCH [TOKEN, SENTENCE, POS, LEMMA, NER]
2020-08-31 15:10:48,626 [CORENLP-0] INFO  NlpConsumer - extracting CORENLP entities for document db0f1d30d53ea9ce1e23f85a21caa19253dead921c701795c067837866f0ded32a0490ff14d6f476d4c7512a9db0eb88
2020-08-31 15:10:48,627 [CORENLP-0] INFO  CorenlpPipeline - initializing CORENLP Skipping... Stage unsupported for DUTCH [TOKEN, SENTENCE, POS, LEMMA, NER]
2020-08-31 15:10:48,646 [CORENLP-0] INFO  NlpConsumer - extracting CORENLP entities for document 4ad06d8976606a344e22ba0da559ba1edda881ed7956e3ad512348fa0bb92668435e8056de06a607c3f08b0cb1450c2d
2020-08-31 15:10:48,646 [CORENLP-0] INFO  CorenlpPipeline - initializing CORENLP Skipping... Stage unsupported for DUTCH [TOKEN, SENTENCE, POS, LEMMA, NER]
2020-08-31 15:10:48,712 [CORENLP-0] INFO  NlpConsumer - extracting CORENLP entities for document 0bad8080b73ee3c1787e26aec5488c1703b6c74557cc29ad4a2761e03123c8980d91acf9c8a14612e3ebbaf80061b183
2020-08-31 15:10:48,713 [CORENLP-0] INFO  CorenlpPipeline - initializing CORENLP Skipping... Stage unsupported for DUTCH [TOKEN, SENTENCE, POS, LEMMA, NER]
2020-08-31 15:10:48,721 [CORENLP-0] INFO  NlpConsumer - extracting CORENLP entities for document d109b2368c0dc6b27a8b1f36012f1381e31a202b0aa50d08ff38a8b3ebfea79405f3e90978a1bab3b30f7b5287c59164
2020-08-31 15:10:48,744 [CORENLP-0] INFO  CorenlpPipeline - initializing CORENLP ENGLISH [TOKEN, SENTENCE, POS, LEMMA, NER]
2020-08-31 15:10:49,069 [CORENLP-0] INFO  CoreNlpNerModels - downloading models for language ENGLISH under dist/models/corenlp/4-0-0/en
2020-08-31 15:11:36,330 [CORENLP-0] INFO  **CoreNlpNerModels - models successfully downloaded for language ENGLISH**
2020-08-31 15:11:36,334 [CORENLP-0] INFO  CoreNlpNerModels - adding models\corenlp\4-0-0\en\stanford-corenlp-4.0.0-models-en.jar to system classloader
2020-08-31 15:11:36,461 [CORENLP-0] **ERROR CoreNlpNerModels - failed loading NER**
java.io.IOException: Unable to open "edu\stanford\nlp\models\ner\english.all.3class.caseless.distsim.crf.ser.gz" as class path, filename or URL
        at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:481)
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1505)
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1497)
        at edu.stanford.nlp.ie.crf.CRFClassifier.getClassifier(CRFClassifier.java:2888)
        at org.icij.datashare.text.nlp.corenlp.models.CoreNlpNerModels.loadModelFile(CoreNlpNerModels.java:75)
        at org.icij.datashare.text.nlp.corenlp.models.CoreNlpNerModels.loadModelFile(CoreNlpNerModels.java:39)
        at org.icij.datashare.text.nlp.AbstractModels.load(AbstractModels.java:59)
        at org.icij.datashare.text.nlp.AbstractModels.get(AbstractModels.java:46)
        at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.initializeNerAnnotator(CorenlpPipeline.java:179)
        at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.initialize(CorenlpPipeline.java:79)
        at org.icij.datashare.nlp.NlpConsumer.findNamedEntities(NlpConsumer.java:72)
        at org.icij.datashare.nlp.NlpConsumer.call(NlpConsumer.java:43)
        at org.icij.datashare.nlp.NlpConsumer.call(NlpConsumer.java:20)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-08-31 15:11:36,464 [CORENLP-0] INFO  CorenlpPipeline - name-finding for ENGLISH
2020-08-31 15:11:36,600 [CORENLP-0] INFO  CoreNlpNerModels - downloading models for language ENGLISH under dist/models/corenlp/4-0-0/en
2020-08-31 15:12:25,594 [CORENLP-0] INFO  **CoreNlpNerModels - models successfully downloaded for language ENGLISH**
2020-08-31 15:12:25,597 [CORENLP-0] INFO  CoreNlpNerModels - adding models\corenlp\4-0-0\en\stanford-corenlp-4.0.0-models-en.jar to system classloader
2020-08-31 15:12:25,602 [CORENLP-0] **ERROR CoreNlpNerModels - failed loading NER**
java.io.IOException: Unable to open "edu\stanford\nlp\models\ner\english.all.3class.caseless.distsim.crf.ser.gz" as class path, filename or URL
        at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:481)
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1505)
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1497)
        at edu.stanford.nlp.ie.crf.CRFClassifier.getClassifier(CRFClassifier.java:2888)
        at org.icij.datashare.text.nlp.corenlp.models.CoreNlpNerModels.loadModelFile(CoreNlpNerModels.java:75)
        at org.icij.datashare.text.nlp.corenlp.models.CoreNlpNerModels.loadModelFile(CoreNlpNerModels.java:39)
        at org.icij.datashare.text.nlp.AbstractModels.load(AbstractModels.java:59)
        at org.icij.datashare.text.nlp.AbstractModels.get(AbstractModels.java:46)
        at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.processNerClassifier(CorenlpPipeline.java:196)
        at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.process(CorenlpPipeline.java:91)
        at org.icij.datashare.nlp.NlpConsumer.findNamedEntities(NlpConsumer.java:73)
        at org.icij.datashare.nlp.NlpConsumer.call(NlpConsumer.java:43)
        at org.icij.datashare.nlp.NlpConsumer.call(NlpConsumer.java:20)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-08-31 15:12:25,604 [CORENLP-0] WARN  NlpConsumer - error in consumer main loop
java.lang.NullPointerException: null
        at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.processNerClassifier(CorenlpPipeline.java:197)
        at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.process(CorenlpPipeline.java:91)
        at org.icij.datashare.nlp.NlpConsumer.findNamedEntities(NlpConsumer.java:73)
        at org.icij.datashare.nlp.NlpConsumer.call(NlpConsumer.java:43)
        at org.icij.datashare.nlp.NlpConsumer.call(NlpConsumer.java:20)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-08-31 15:12:25,627 [CORENLP-0] INFO  NlpConsumer - extracting CORENLP entities for document be436e76eabeac1927f5650069254cedb9e399369b1eed0deb037b1d6a15743ed603abe221d3e25d5d9f3d8dfeb49d69
2020-08-31 15:12:25,633 [CORENLP-0] INFO  CorenlpPipeline - initializing CORENLP Skipping... Stage unsupported for DUTCH [TOKEN, SENTENCE, POS, LEMMA, NER]
2020-08-31 15:12:25,646 [CORENLP-0] INFO  NlpConsumer - extracting CORENLP entities for document 459ce1df825d52d3543e8acbbb0b08aba883c87f37aa16c86a23b145fe5651e3eaf4e58466ddf97e1584763125d57cc9
2020-08-31 15:12:25,646 [CORENLP-0] INFO  CorenlpPipeline - initializing CORENLP Skipping... Stage unsupported for DUTCH [TOKEN, SENTENCE, POS, LEMMA, NER]
2020-08-31 15:12:25,652 [CORENLP-0] INFO  NlpConsumer - extracting CORENLP entities for document 75adb83e6dc317c361de65f5604b8e265a6640aaa36548cf0e3b95c2bdf5300ded52cf7628174ba04e24970a31e8591f
2020-08-31 15:12:25,665 [CORENLP-0] INFO  CorenlpPipeline - initializing CORENLP Skipping... Stage unsupported for DUTCH [TOKEN, SENTENCE, POS, LEMMA, NER]
2020-08-31 15:12:25,673 [CORENLP-0] INFO  NlpConsumer - extracting CORENLP entities for document 2128bf7f0fe3c8927539c31944fc9cd12df10302c1485b8a84707aea4d0e3b571de219c91ac40f3c99afb0d6c81d18c7
2020-08-31 15:12:25,681 [CORENLP-0] INFO  CorenlpPipeline - initializing CORENLP Skipping... Stage unsupported for DUTCH [TOKEN, SENTENCE, POS, LEMMA, NER]
2020-08-31 15:12:25,698 [CORENLP-0] INFO  NlpConsumer - extracting CORENLP entities for document b94c84affa93b5e57d20d873d0e44548635bd47a2080095fe7ca1f024d94addab42d6238c639ec073d83afb3f3b20081
2020-08-31 15:12:25,698 [CORENLP-0] INFO  CorenlpPipeline - initializing CORENLP Skipping... Stage unsupported for DUTCH [TOKEN, SENTENCE, POS, LEMMA, NER]
2020-08-31 15:12:25,728 [CORENLP-0] INFO  NlpConsumer - extracting CORENLP entities for document 9edea6e1be557b2441e979a94bfd2fdff50465eb242b58e3e4c67b9b5e7a8deff4bb11fd04fe25aba45df511e4cc4bd7
2020-08-31 15:12:25,729 [CORENLP-0] INFO  CorenlpPipeline - initializing CORENLP Skipping... Stage unsupported for DUTCH [TOKEN, SENTENCE, POS, LEMMA, NER]
2020-08-31 15:12:25,745 [CORENLP-0] INFO  NlpConsumer - extracting CORENLP entities for document 43d2639c4ab4390add59d49d4db1ea57339751f8f20549c6c05ba282526974541fdfdf924dedfdb4cafd3a6cc5cc1eb0
2020-08-31 15:12:25,745 [CORENLP-0] INFO  CorenlpPipeline - initializing CORENLP Skipping... Stage unsupported for DUTCH [TOKEN, SENTENCE, POS, LEMMA, NER]
2020-08-31 15:12:25,747 [CORENLP-0] INFO  NlpConsumer - exiting main loop
2020-08-31 15:12:25,762 [pool-2-thread-1] INFO  NlpApp - exiting run

**Comment by bamthomas** [comment]
my guess would be that it doesn't locate correctly where the jar is installed. It could be an installation problem.
