### ISSUE TITLE
Can't extract named entities

### ISSUE THREAD

**Issue by Julm** [ICIJ/datashare#598]
**Describe the bug**
Named entities extraction does not work; seemingly because Core NLP models can't be downloaded.

**To Reproduce**
0. Put a document in the data dir
1. Go to 'Analyse your documents'
2. Click on 'Extract text'
3. Click on 'Find people...'
4. See error: 
```
2020-08-20 10:23:20,753 [Worker: RequestDispatcher: Thread-25] INFO  AbstractModels - synchronize models is set to true
2020-08-20 10:23:20,755 [Worker: RequestDispatcher: Thread-25] INFO  TaskResource - waiting for NlpApp org.icij.datashare.text.nlp.corenlp.CorenlpPipeline@294f811c to listen...
2020-08-20 10:23:20,755 [pool-2-thread-3] INFO  NlpApp - running NlpApp for CORENLP pipeline with 1 thread(s)
2020-08-20 10:23:20,758 [Worker: RequestDispatcher: Thread-25] INFO  TaskResource - ...org.icij.datashare.text.nlp.corenlp.CorenlpPipeline@294f811c is listening
2020-08-20 10:23:20,760 [pool-2-thread-4] INFO  ResumeNlpTask - resuming NLP name finding for index local-datashare and [CORENLP]
2020-08-20 10:23:20,833 [pool-2-thread-4] INFO  ResumeNlpTask - sent EXTRACT_NLP message for 1 files without [CORENLP] pipeline tags
2020-08-20 10:23:20,839 [CORENLP-0] INFO  NlpConsumer - extracting CORENLP entities for document cc50f108ccc39835b7df3cb0927744da384d2e654b6cedc740a5d9272fec397652ed8a41a4bf0e02ab4ccf7c24926935
2020-08-20 10:23:20,839 [pool-2-thread-3] INFO  MemoryDataBus - exiting org.icij.datashare.nlp.NlpForwarder$$Lambda$2354/162604664@30a9ed34
2020-08-20 10:23:20,840 [pool-2-thread-3] INFO  NlpApp - forwarder exited waiting for consumer(s) to finish
2020-08-20 10:23:20,841 [CORENLP-0] INFO  CorenlpPipeline - initializing CORENLP ENGLISH [TOKEN, SENTENCE, POS, LEMMA, NER]
2020-08-20 10:23:21,006 [CORENLP-0] INFO  CoreNlpNerModels - downloading models for language ENGLISH under dist/models/corenlp/4-0-0/en
2020-08-20 10:23:21,564 [CORENLP-0] WARN  NlpConsumer - error in consumer main loop
com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 6DFD3057AD174153; S3 Extended Request ID: ObQtuh5342zb5XcjARRtnRiuD5mbSMILK7gb0jlpcy7MAS99bmFAY/ZrsEWidV16k1xTGi+x120=)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1632)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1058)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4365)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4312)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4306)
        at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:840)
        at com.amazonaws.services.s3.transfer.TransferManager.downloadDirectory(TransferManager.java:1211)
        at com.amazonaws.services.s3.transfer.TransferManager.downloadDirectory(TransferManager.java:1157)
        at com.amazonaws.services.s3.transfer.TransferManager.downloadDirectory(TransferManager.java:1148)
        at org.icij.datashare.io.RemoteFiles.download(RemoteFiles.java:76)
        at org.icij.datashare.text.nlp.AbstractModels.downloadIfNecessary(AbstractModels.java:98)
        at org.icij.datashare.text.nlp.AbstractModels.load(AbstractModels.java:57)
        at org.icij.datashare.text.nlp.AbstractModels.get(AbstractModels.java:46)
        at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.initializeNerAnnotator(CorenlpPipeline.java:179)
        at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.initialize(CorenlpPipeline.java:79)
        at org.icij.datashare.nlp.NlpConsumer.findNamedEntities(NlpConsumer.java:72)
        at org.icij.datashare.nlp.NlpConsumer.call(NlpConsumer.java:43)
        at org.icij.datashare.nlp.NlpConsumer.call(NlpConsumer.java:20)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-08-20 10:23:21,564 [CORENLP-0] INFO  NlpConsumer - exiting main loop
2020-08-20 10:23:21,567 [pool-2-thread-3] INFO  NlpApp - exiting run
```

**Expected behavior**
I guess you know.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: Datashare 7.5.3

**Comment by Soliine** [comment]
Hello Julien! Thanks for opening this issue. I link it with https://github.com/ICIJ/datashare/issues/587. Bruno and Maxime are going to look into this and we'll let you know when it is fixed as soon as possible. Thanks again and talk to you soon!

**Comment by Julm** [comment]
Hi Soliiiine, Hi everyone, hope you're all doing fine.

Thanks for looking at it.

Let's see each other soon.

**Comment by bamthomas** [comment]
I should work now

**Comment by Julm** [comment]
Hi there!

Thanks.

Well, as a matter of fact, it seems that this issue is fixed (7.8.0), yes, but I'm opening another; now it can't load the model.
