### ISSUE TITLE
Datashare cannot filter/search on special characters

### ISSUE THREAD

**Issue by nodearcnode** [ICIJ/datashare#618]
**Describe the bug**
My filter contains the value 'aivd.nl/inzageverzoeken' , but this value cannot be parsed  (see bold logging) and no filtering is possible

**To Reproduce**
1. I parsed my own values into the ES-index under the custom NamedEntity-category 'URL' with a custom plugin for a URL-filter
2. Select value 'aivd.nl/inzageverzoeken' in Filter

![image](https://user-images.githubusercontent.com/6241380/91838812-5d96f580-ec4e-11ea-9612-c53c50e87456.png)

**Expected behavior**
back- and forward slashes, but also other punctuation should also be handled as valid input to Elastic Search; URL-encode the value might work

 / **OR** %2F **OR** %2F%2F **doesnt work**
- http://127.0.0.1:9200/local-datashare/_search?q=type:NamedEntity%20AND%20category:URL%20AND%20mentionNorm:aivd.nl/inzageverzoeken **this causes the error** 
- http://127.0.0.1:9200/local-datashare/_search?q=type:NamedEntity%20AND%20category:URL%20AND%20mentionNorm:aivd.nl/%2Finzageverzoeken
- http://127.0.0.1:9200/local-datashare/_search?q=type:NamedEntity%20AND%20category:URL%20AND%20mentionNorm:aivd.nl%2F%2Finzageverzoeken

**URL-encoding: an encoded backslash before the encoded special character works in this case**
- http://127.0.0.1:9200/local-datashare/_search?q=type:NamedEntity%20AND%20category:URL%20AND%20mentionNorm:aivd.nl%5C%2Finzageverzoeken

**Screenshots**
![image](https://user-images.githubusercontent.com/6241380/91838464-da759f80-ec4d-11ea-85db-51acf284f2d2.png)

Also other special characters cause filtering problems, e.g. the PERSON 'Abdullah Öçalan' (it has documents)
![image](https://user-images.githubusercontent.com/6241380/91839120-d5652000-ec4e-11ea-917c-028674e711d0.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: Chrome
 - Version: 7.7.3

**Logging**
2020-09-01 11:47:43,399 [Worker: RequestDispatcher: Thread-29] INFO  PluginService - detected plugin <datashare-plugin-url-filter> with index.js
2020-09-01 11:47:44,866 [Worker: RequestDispatcher: Thread-29] ERROR Fluent - Unable to POST /api/index/search/local-datashare/doc/_search
2020-09-01 11:47:44,868 [Worker: RequestDispatcher: Thread-29] ERROR Fluent - Unexpected error:
java.lang.IllegalStateException: Unable to apply route
        at net.codestory.http.routes.ReflectionRoute.lambda$body$0(ReflectionRoute.java:54)
        at net.codestory.http.annotations.MethodAnnotations.apply(MethodAnnotations.java:48)
        at net.codestory.http.routes.ReflectionRoute.body(ReflectionRoute.java:40)
        at net.codestory.http.routes.RouteWithPattern.body(RouteWithPattern.java:56)
        at net.codestory.http.routes.Route.apply(Route.java:25)
        at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$98caf044$1(RouteCollection.java:577)
        at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
        at org.icij.datashare.session.LocalUserFilter.otherUri(LocalUserFilter.java:30)
        at net.codestory.http.filters.auth.CookieAuthFilter.apply(CookieAuthFilter.java:78)
        at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
        at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
        at org.icij.datashare.web.IndexWaiterFilter.apply(IndexWaiterFilter.java:43)
        at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
        at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
        at org.icij.datashare.session.LocalUserFilter.otherUri(LocalUserFilter.java:30)
        at net.codestory.http.filters.auth.CookieAuthFilter.apply(CookieAuthFilter.java:78)
        at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
        at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
        at org.icij.datashare.web.IndexWaiterFilter.apply(IndexWaiterFilter.java:43)
        at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
        at net.codestory.http.routes.RouteCollection.apply(RouteCollection.java:567)
        at net.codestory.http.AbstractWebServer.handleHttp(AbstractWebServer.java:152)
        at net.codestory.http.internal.SimpleServerWrapper.handle(SimpleServerWrapper.java:71)
        at org.simpleframework.http.socket.service.RouterContainer.handle(RouterContainer.java:106)
        at org.simpleframework.http.core.RequestDispatcher.dispatch(RequestDispatcher.java:121)
        at org.simpleframework.http.core.RequestDispatcher.run(RequestDispatcher.java:103)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.elasticsearch.client.ResponseException: method [POST], host [http://localhost:9200], URI [/local-datashare/doc/_search], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"query_shard_exception","reason":"Failed to parse query [(**aivd.nl/inzageverzoeken**)]","index_uuid":"V_LjzHs1TPKnSJft69op3Q","index":"local-datashare"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"local-datashare","node":"1ENnQHIgTeWO_KXjX_2-ng","reason":{"type":"query_shard_exception","reason":"Failed to parse query [(aivd.nl/inzageverzoeken)]","index_uuid":"V_LjzHs1TPKnSJft69op3Q","index":"local-datashare","caused_by":{"type":"parse_exception","reason":"**Cannot parse '(aivd.nl/inzageverzoeken)': Lexical error at line 1, column 26.  Encountered: <EOF> after : \"/inzageverzoeken)\"","caused_by":{"type":"token_mgr_error","reason":"Lexical error at line 1, column 26.  Encountered: <EOF> after : \"/inzageverzoeken**)\""}}}}]},"status":400}
        at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:926)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:229)
        at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchIndexer.executeRaw(ElasticsearchIndexer.java:165)
        at org.icij.datashare.web.IndexResource.esPost(IndexResource.java:84)
        at sun.reflect.GeneratedMethodAccessor231.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.codestory.http.routes.ReflectionRoute.invoke(ReflectionRoute.java:83)
        at net.codestory.http.routes.ReflectionRoute.lambda$body$0(ReflectionRoute.java:45)
        ... 28 common frames omitted
Caused by: org.elasticsearch.client.ResponseException: method [POST], host [http://localhost:9200], URI [/local-datashare/doc/_search], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"query_shard_exception","reason":"Failed to parse query [(aivd.nl/inzageverzoeken)]","index_uuid":"V_LjzHs1TPKnSJft69op3Q","index":"local-datashare"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"local-datashare","node":"1ENnQHIgTeWO_KXjX_2-ng","reason":{"type":"query_shard_exception","reason":"Failed to parse query [(aivd.nl/inzageverzoeken)]","index_uuid":"V_LjzHs1TPKnSJft69op3Q","index":"local-datashare","caused_by":{"type":"parse_exception","reason":"Cannot parse '(aivd.nl/inzageverzoeken)': Lexical error at line 1, column 26.  Encountered: <EOF> after : \"/inzageverzoeken)\"","caused_by":{"type":"token_mgr_error","reason":"Lexical error at line 1, column 26.  Encountered: <EOF> after : \"/inzageverzoeken)\""}}}}]},"status":400}
        at org.elasticsearch.client.RestClient$1.completed(RestClient.java:546)
        at org.elasticsearch.client.RestClient$1.completed(RestClient.java:531)
        at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:123)
        at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
        at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
        ... 1 common frames omitted

**Comment by Soliine** [comment]
I can't reproduce the issue "Other special characters cause filtering problems, e.g. the PERSON 'Abdullah Öçalan' (it has documents)", because there is no special characters nor accents in Datashare-generated named entities.

**Comment by Soliine** [comment]
To create filters on a field, ES runs tokenization. When it is done with special characters, if one searches the special characters, it won't find it in the filters.
In the search, ES, by default, doesn't search all characters but only unicode characters. If we want additional parsers, we need to use language specific parsers. We can't add all of them at the moment.
