### ISSUE TITLE
No NLP entities showing up in the filter menu 

### ISSUE THREAD

**Issue by MatiasConTilde** [ICIJ/datashare#642]
**Describe the bug**
When clicking on the + sign in the people, organizations or location filter menus, no list shows up, even if there are entieties scanned.
![image](https://user-images.githubusercontent.com/7951833/94018238-a99e0b80-fdb0-11ea-9878-41259d47beed.png)

**To Reproduce**
1. I have indexed ~4M documents and run NLP on them
2. RAM for each elsticsearch node is 32GB (`ES_JAVA_OPTS=-Xms32g -Xmx32g`)

**Expected behavior**
A list of the entities to show up without throwing errors

**Things I've tried:**
When I had fewer documents indexed, everything worked just fine. At some point, this bug apeared and when I gave it more RAM, it worked again. The problem now is that there is no more RAM left on the server.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox, but it's irrelevant
 - Version: e.g. 7.9.5

**Additional context**
logs are:
```
datashare_1       | 2020-09-23 13:22:13,169 [Worker: RequestDispatcher: Thread-32] ERROR Fluent - Unable to POST /api/index/search/local-datashare/doc/_search
datashare_1       | 2020-09-23 13:22:13,171 [Worker: RequestDispatcher: Thread-32] ERROR Fluent - Unexpected error:
datashare_1       | java.lang.IllegalStateException: Unable to apply route
datashare_1       |     at net.codestory.http.routes.ReflectionRoute.lambda$body$0(ReflectionRoute.java:54)
datashare_1       |     at net.codestory.http.annotations.MethodAnnotations.apply(MethodAnnotations.java:48)
datashare_1       |     at net.codestory.http.routes.ReflectionRoute.body(ReflectionRoute.java:40)
datashare_1       |     at net.codestory.http.routes.RouteWithPattern.body(RouteWithPattern.java:56)
datashare_1       |     at net.codestory.http.routes.Route.apply(Route.java:25)
datashare_1       |     at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$98caf044$1(RouteCollection.java:577)
datashare_1       |     at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
datashare_1       |     at org.icij.datashare.session.LocalUserFilter.otherUri(LocalUserFilter.java:30)
datashare_1       |     at net.codestory.http.filters.auth.CookieAuthFilter.apply(CookieAuthFilter.java:78)
datashare_1       |     at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
datashare_1       |     at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
datashare_1       |     at org.icij.datashare.web.IndexWaiterFilter.apply(IndexWaiterFilter.java:43)
datashare_1       |     at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
datashare_1       |     at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
datashare_1       |     at org.icij.datashare.session.LocalUserFilter.otherUri(LocalUserFilter.java:30)
datashare_1       |     at net.codestory.http.filters.auth.CookieAuthFilter.apply(CookieAuthFilter.java:78)
datashare_1       |     at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
datashare_1       |     at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
datashare_1       |     at org.icij.datashare.web.IndexWaiterFilter.apply(IndexWaiterFilter.java:43)
datashare_1       |     at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
datashare_1       |     at net.codestory.http.routes.RouteCollection.apply(RouteCollection.java:567)
datashare_1       |     at net.codestory.http.AbstractWebServer.handleHttp(AbstractWebServer.java:152)
datashare_1       |     at net.codestory.http.internal.SimpleServerWrapper.handle(SimpleServerWrapper.java:71)
datashare_1       |     at org.simpleframework.http.socket.service.RouterContainer.handle(RouterContainer.java:106)
datashare_1       |     at org.simpleframework.http.core.RequestDispatcher.dispatch(RequestDispatcher.java:121)
datashare_1       |     at org.simpleframework.http.core.RequestDispatcher.run(RequestDispatcher.java:103)
datashare_1       |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
datashare_1       |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
datashare_1       |     at java.lang.Thread.run(Thread.java:748)
datashare_1       | Caused by: org.elasticsearch.client.ResponseException: method [POST], host [http://elasticsearch:9200], URI [/local-datashare/doc/_search], status line [HTTP/1.1 503 Service Unavailable]
datashare_1       | {"error":{"root_cause":[{"type":"circuit_breaking_exception","reason":"[request] Data too large, data for [<reused_arrays>] would be [21301617984/19.8gb], which is larger than the limit of [20615843020/19.1gb]","bytes_wanted":21301617984,"bytes_limi
t":20615843020}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"local-datashare","node":"zsLeJaeKQI-mytaxC3HZzA","reason":{"type":"circuit_breaking_exception","reason":"[request
] Data too large, data for [<reused_arrays>] would be [21301617984/19.8gb], which is larger than the limit of [20615843020/19.1gb]","bytes_wanted":21301617984,"bytes_limit":20615843020}}]},"status":503}
datashare_1       |     at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:926)
datashare_1       |     at org.elasticsearch.client.RestClient.performRequest(RestClient.java:229)
datashare_1       |     at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchIndexer.executeRaw(ElasticsearchIndexer.java:165)
datashare_1       |     at org.icij.datashare.web.IndexResource.esPost(IndexResource.java:84)
datashare_1       |     at sun.reflect.GeneratedMethodAccessor226.invoke(Unknown Source)
datashare_1       |     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
datashare_1       |     at java.lang.reflect.Method.invoke(Method.java:498)
datashare_1       |     at net.codestory.http.routes.ReflectionRoute.invoke(ReflectionRoute.java:83)
datashare_1       |     at net.codestory.http.routes.ReflectionRoute.lambda$body$0(ReflectionRoute.java:45)
datashare_1       |     ... 28 common frames omitted
datashare_1       | Caused by: org.elasticsearch.client.ResponseException: method [POST], host [http://elasticsearch:9200], URI [/local-datashare/doc/_search], status line [HTTP/1.1 503 Service Unavailable]
datashare_1       | {"error":{"root_cause":[{"type":"circuit_breaking_exception","reason":"[request] Data too large, data for [<reused_arrays>] would be [21301617984/19.8gb], which is larger than the limit of [20615843020/19.1gb]","bytes_wanted":21301617984,"bytes_limi
t":20615843020}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"local-datashare","node":"zsLeJaeKQI-mytaxC3HZzA","reason":{"type":"circuit_breaking_exception","reason":"[request
] Data too large, data for [<reused_arrays>] would be [21301617984/19.8gb], which is larger than the limit of [20615843020/19.1gb]","bytes_wanted":21301617984,"bytes_limit":20615843020}}]},"status":503}
datashare_1       |     at org.elasticsearch.client.RestClient$1.completed(RestClient.java:546)
datashare_1       |     at org.elasticsearch.client.RestClient$1.completed(RestClient.java:531)
datashare_1       |     at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:123)
datashare_1       |     at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
datashare_1       |     at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
datashare_1       |     at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
datashare_1       |     at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
datashare_1       |     at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
datashare_1       |     at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
datashare_1       |     at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
datashare_1       |     at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
datashare_1       |     at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
datashare_1       |     at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
datashare_1       |     at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
datashare_1       |     at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
datashare_1       |     at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
datashare_1       |     ... 1 common frames omitted
datashare_1       | 2020-09-23 13:22:42,084 [Worker: RequestDispatcher: Thread-25] ERROR Fluent - Unable to POST /api/index/search/local-datashare/doc/_search
datashare_1       | 2020-09-23 13:22:42,085 [Worker: RequestDispatcher: Thread-25] ERROR Fluent - Unexpected error:
datashare_1       | java.lang.IllegalStateException: Unable to apply route
datashare_1       |     at net.codestory.http.routes.ReflectionRoute.lambda$body$0(ReflectionRoute.java:54)
datashare_1       |     at net.codestory.http.annotations.MethodAnnotations.apply(MethodAnnotations.java:48)
datashare_1       |     at net.codestory.http.routes.ReflectionRoute.body(ReflectionRoute.java:40)
datashare_1       |     at net.codestory.http.routes.RouteWithPattern.body(RouteWithPattern.java:56)
datashare_1       |     at net.codestory.http.routes.Route.apply(Route.java:25)
datashare_1       |     at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$98caf044$1(RouteCollection.java:577)
datashare_1       |     at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
datashare_1       |     at org.icij.datashare.session.LocalUserFilter.otherUri(LocalUserFilter.java:30)
datashare_1       |     at net.codestory.http.filters.auth.CookieAuthFilter.apply(CookieAuthFilter.java:78)
datashare_1       |     at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
datashare_1       |     at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
datashare_1       |     at org.icij.datashare.web.IndexWaiterFilter.apply(IndexWaiterFilter.java:43)
datashare_1       |     at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
datashare_1       |     at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
datashare_1       |     at org.icij.datashare.session.LocalUserFilter.otherUri(LocalUserFilter.java:30)
datashare_1       |     at net.codestory.http.filters.auth.CookieAuthFilter.apply(CookieAuthFilter.java:78)
datashare_1       |     at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
datashare_1       |     at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
datashare_1       |     at org.icij.datashare.web.IndexWaiterFilter.apply(IndexWaiterFilter.java:43)
datashare_1       |     at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
datashare_1       |     at net.codestory.http.routes.RouteCollection.apply(RouteCollection.java:567)
datashare_1       |     at net.codestory.http.AbstractWebServer.handleHttp(AbstractWebServer.java:152)
datashare_1       |     at net.codestory.http.internal.SimpleServerWrapper.handle(SimpleServerWrapper.java:71)
datashare_1       |     at org.simpleframework.http.socket.service.RouterContainer.handle(RouterContainer.java:106)
datashare_1       |     at org.simpleframework.http.core.RequestDispatcher.dispatch(RequestDispatcher.java:121)
datashare_1       |     at org.simpleframework.http.core.RequestDispatcher.run(RequestDispatcher.java:103)
datashare_1       |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
datashare_1       |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
datashare_1       |     at java.lang.Thread.run(Thread.java:748)
datashare_1       | Caused by: java.io.IOException: listener timeout after waiting for [50000] ms
datashare_1       |     at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:905)
datashare_1       |     at org.elasticsearch.client.RestClient.performRequest(RestClient.java:229)
datashare_1       |     at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchIndexer.executeRaw(ElasticsearchIndexer.java:165)
datashare_1       |     at org.icij.datashare.web.IndexResource.esPost(IndexResource.java:84)
datashare_1       |     at sun.reflect.GeneratedMethodAccessor226.invoke(Unknown Source)
datashare_1       |     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
datashare_1       |     at java.lang.reflect.Method.invoke(Method.java:498)
datashare_1       |     at net.codestory.http.routes.ReflectionRoute.invoke(ReflectionRoute.java:83)
datashare_1       |     at net.codestory.http.routes.ReflectionRoute.lambda$body$0(ReflectionRoute.java:45)
datashare_1       |     ... 28 common frames omitted
```

**Comment by pirhoo** [comment]
Closed in favor of https://github.com/ICIJ/datashare/issues/665 and https://github.com/ICIJ/datashare/issues/727
