### ISSUE TITLE
Download source document for 3rd level of embedding ZIP > MSG > PDF

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#732]
**Describe the bug**

We've seen that in A most of the time when there is a PDF file embedded in an embedded document, then DS fails to extract it.

**To Reproduce**

Here we opened a PDF contained in a MSG email file in a ZIP.

```
org.icij.extract.extractor.EmbeddedDocumentMemoryExtractor$ContentNotFoundException: ...embedded document not found in root document...
at org.icij.extract.extractor.EmbeddedDocumentMemoryExtractor$DigestEmbeddedDocumentExtractor.lambda$getDocument$0(EmbeddedDocumentMemoryExtractor.java:100)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.icij.extract.extractor.EmbeddedDocumentMemoryExtractor$DigestEmbeddedDocumentExtractor.getDocument(EmbeddedDocumentMemoryExtractor.java:99)
	at org.icij.extract.extractor.EmbeddedDocumentMemoryExtractor.extract(EmbeddedDocumentMemoryExtractor.java:50)
	at org.icij.datashare.text.indexing.elasticsearch.SourceExtractor.getSource(SourceExtractor.java:47)
	at org.icij.datashare.web.DocumentResource.getPayload(DocumentResource.java:350)
	at org.icij.datashare.web.DocumentResource.getSourceFile(DocumentResource.java:72)
			3 lines skipped for [sun., java.lang.reflect.Method]
	at net.codestory.http.routes.ReflectionRoute.invoke(ReflectionRoute.java:83)
	at net.codestory.http.routes.ReflectionRoute.lambda$body$0(ReflectionRoute.java:45)
	at net.codestory.http.annotations.MethodAnnotations.apply(MethodAnnotations.java:48)
	at net.codestory.http.routes.ReflectionRoute.body(ReflectionRoute.java:40)
```

**Expected behavior**

The PDF data should be returned

**Comment by bamthomas** [comment]
see #564
