### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by kylemcdonald** [ICIJ/datashare#742]
**Describe the bug**
When I run ./datashare.sh and go to http://localhost:8080/ I immediately see the error "Request failed with status code 500"

**To Reproduce**
1. Install docker and docker-composer.
2. `wget https://github.com/ICIJ/datashare-installer/releases/download/8.5.1/datashare.sh`
3. `./datashare.sh`
4. Open a browser and navigate to http://localhost:8080/

**Expected behavior**
I expect to see the Datashare interface.

**Screenshots**
<img width="845" alt="Screen Shot 2021-01-29 at 5 29 21 PM" src="https://user-images.githubusercontent.com/157106/106342872-8cde7c80-6257-11eb-84e3-69a15e1de0c5.png">

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: 8.5.1 and 8.6.0
 - Docker version 20.10.2, build 2291f61
 - docker-compose version 1.17.1, build unknown

```console
$ bash datashare.sh
datashare_elasticsearch_1 is up-to-date
datashare_redis_1 is up-to-date
binding data directory to
binding NER models directory to /home/kyle/.local/share/datashare/dist
2021-01-30 01:27:28,033 [main] INFO  Main - Running datashare web server
2021-01-30 01:27:28,040 [main] WARN  PropertiesProvider - no null file found, using default values
2021-01-30 01:27:28,117 [main] INFO  PropertiesProvider - adding properties from env vars {mountedDataDir=/home/kyle/Datashare}
2021-01-30 01:27:28,117 [main] INFO  PropertiesProvider - properties set to {mountedDataDir=/home/kyle/Datashare}
2021-01-30 01:27:28,117 [main] INFO  PropertiesProvider - merged properties (without override) with {tcpListenPort=8080, scrollSize=1000, elasticsearchAddress=http://elasticsearch:9200, queueName=extract:queue, browserOpenLink=false, sessionTtlSeconds=43200, scrollSlices=1, queueType=redis, protectedUriPrefix=/api/, cors=no-cors, mode=LOCAL, redisPoolSize=1, redisAddress=redis://redis:6379, extensionsDir=/home/datashare/extensions, defaultUserName=local, ocr=true, nlpParallelism=1, parserParallelism=1, dataSourceUrl=jdbc:sqlite:/home/datashare/dist/database.sqlite, defaultProject=local-datashare, elasticsearchDataPath=/home/datashare/es, dataDir=/home/datashare/data, pluginsDir=/home/datashare/plugins, clusterName=datashare, busType=redis, messageBusAddress=redis, parallelism=12}
2021-01-30 01:27:28,714 [Thread-0] INFO  ExtensionLoader - read directory /home/datashare/extensions and found jars (executable): []
2021-01-30 01:27:28,731 [Thread-0] INFO  HikariDataSource - HikariPool-1 - Starting...
2021-01-30 01:27:28,864 [Thread-0] INFO  HikariDataSource - HikariPool-1 - Start completed.
2021-01-30 01:27:28,937 [Thread-0] INFO  HikariDataSource - HikariPool-2 - Starting...
2021-01-30 01:27:28,938 [Thread-0] INFO  HikariDataSource - HikariPool-2 - Start completed.
2021-01-30 01:27:28,941 [Thread-0] INFO  HikariDataSource - HikariPool-3 - Starting...
2021-01-30 01:27:28,942 [Thread-0] INFO  HikariDataSource - HikariPool-3 - Start completed.
2021-01-30 01:27:28,959 [Thread-0] INFO  HikariDataSource - HikariPool-4 - Starting...
2021-01-30 01:27:28,960 [Thread-0] INFO  HikariDataSource - HikariPool-4 - Start completed.
2021-01-30 01:27:33,169 [Thread-0] INFO  JdbcExecutor - SELECT COUNT(*) FROM DATABASECHANGELOGLOCK
2021-01-30 01:27:33,174 [Thread-0] INFO  JdbcExecutor - SELECT COUNT(*) FROM DATABASECHANGELOGLOCK
2021-01-30 01:27:33,178 [Thread-0] INFO  JdbcExecutor - SELECT LOCKED FROM DATABASECHANGELOGLOCK WHERE ID=1
2021-01-30 01:27:33,198 [Thread-0] INFO  StandardLockService - Successfully acquired change log lock
2021-01-30 01:27:33,852 [Thread-0] INFO  JdbcExecutor - SELECT MD5SUM FROM DATABASECHANGELOG WHERE MD5SUM IS NOT NULL
2021-01-30 01:27:33,853 [Thread-0] INFO  JdbcExecutor - SELECT COUNT(*) FROM DATABASECHANGELOG
2021-01-30 01:27:33,853 [Thread-0] INFO  StandardChangeLogHistoryService - Reading from DATABASECHANGELOG
2021-01-30 01:27:33,853 [Thread-0] INFO  JdbcExecutor - SELECT * FROM DATABASECHANGELOG ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2021-01-30 01:27:33,917 [Thread-0] INFO  StandardLockService - Successfully released change log lock
2021-01-30 01:27:33,917 [Thread-0] INFO  HikariDataSource - HikariPool-4 - Shutdown initiated...
2021-01-30 01:27:33,921 [Thread-0] INFO  HikariDataSource - HikariPool-4 - Shutdown completed.
2021-01-30 01:27:34,102 [Thread-0] INFO  Indexer - indexer defined with cfg{indexType='doc', indexJoinField='join', docTypeField='type', shards=1, replicas=1}
2021-01-30 01:27:34,282 [pool-3-thread-1] INFO  IndexWaiterFilter - Ping elasticsearch succeeded
2021-01-30 01:27:34,570 [redisson-netty-2-5] INFO  MasterConnectionPool - 1 connections initialized for redis/172.18.0.3:6379
2021-01-30 01:27:34,570 [redisson-netty-2-6] INFO  MasterPubSubConnectionPool - 1 connections initialized for redis/172.18.0.3:6379
2021-01-30 01:27:34,620 [Thread-0] INFO  ExtensionLoader - read directory /home/datashare/extensions and found jars (executable): []
2021-01-30 01:27:35,035 [Thread-0] INFO  Fluent - Production mode
2021-01-30 01:27:35,049 [Thread-0] INFO  Fluent - Server started on port 8080
2021-01-30 01:28:03,596 [Worker: RequestDispatcher: Thread-33] ERROR Fluent - Unable to PUT /api/index/local-datashare
2021-01-30 01:28:03,598 [Worker: RequestDispatcher: Thread-33] ERROR Fluent - Unexpected error:
org.elasticsearch.ElasticsearchStatusException: method [HEAD], host [http://elasticsearch:9200], URI [/local-datashare?include_type_name=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true], status line [HTTP/1.1 400 Bad Request]
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2027)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1777)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1734)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1717)
	at org.elasticsearch.client.IndicesClient.exists(IndicesClient.java:1128)
	at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchConfiguration.createIndex(ElasticsearchConfiguration.java:85)
	at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchIndexer.createIndex(ElasticsearchIndexer.java:298)
	at org.icij.datashare.web.IndexResource.createIndex(IndexResource.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.codestory.http.routes.ReflectionRoute.invoke(ReflectionRoute.java:83)
	at net.codestory.http.routes.ReflectionRoute.lambda$body$0(ReflectionRoute.java:45)
	at net.codestory.http.annotations.MethodAnnotations.apply(MethodAnnotations.java:48)
	at net.codestory.http.routes.ReflectionRoute.body(ReflectionRoute.java:40)
	at net.codestory.http.routes.RouteWithPattern.body(RouteWithPattern.java:56)
	at net.codestory.http.routes.Route.apply(Route.java:25)
	at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$98caf044$1(RouteCollection.java:577)
	at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
	at org.icij.datashare.session.LocalUserFilter.otherUri(LocalUserFilter.java:30)
	at net.codestory.http.filters.auth.CookieAuthFilter.apply(CookieAuthFilter.java:78)
	at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
	at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
	at org.icij.datashare.web.IndexWaiterFilter.apply(IndexWaiterFilter.java:43)
	at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
	at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
	at org.icij.datashare.session.LocalUserFilter.otherUri(LocalUserFilter.java:30)
	at net.codestory.http.filters.auth.CookieAuthFilter.apply(CookieAuthFilter.java:78)
	at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
	at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
	at org.icij.datashare.web.IndexWaiterFilter.apply(IndexWaiterFilter.java:43)
	at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
	at net.codestory.http.routes.RouteCollection.apply(RouteCollection.java:567)
	at net.codestory.http.AbstractWebServer.handleHttp(AbstractWebServer.java:152)
	at net.codestory.http.internal.SimpleServerWrapper.handle(SimpleServerWrapper.java:71)
	at org.simpleframework.http.socket.service.RouterContainer.handle(RouterContainer.java:106)
	at org.simpleframework.http.core.RequestDispatcher.dispatch(RequestDispatcher.java:121)
	at org.simpleframework.http.core.RequestDispatcher.run(RequestDispatcher.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.elasticsearch.client.ResponseException: method [HEAD], host [http://elasticsearch:9200], URI [/local-datashare?include_type_name=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true], status line [HTTP/1.1 400 Bad Request]
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:936)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:233)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1764)
	... 40 common frames omitted
Caused by: org.elasticsearch.client.ResponseException: method [HEAD], host [http://elasticsearch:9200], URI [/local-datashare?include_type_name=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true], status line [HTTP/1.1 400 Bad Request]
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:552)
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:537)
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:123)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.responseReceived(HttpAsyncRequestExecutor.java:309)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:255)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	... 1 common frames omitted
2021-01-30 01:28:23,895 [Worker: RequestDispatcher: Thread-19] ERROR Fluent - Unable to PUT /api/index/local-datashare
2021-01-30 01:28:23,896 [Worker: RequestDispatcher: Thread-19] ERROR Fluent - Unexpected error:
org.elasticsearch.ElasticsearchStatusException: method [HEAD], host [http://elasticsearch:9200], URI [/local-datashare?include_type_name=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true], status line [HTTP/1.1 400 Bad Request]
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:2027)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1777)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1734)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1717)
	at org.elasticsearch.client.IndicesClient.exists(IndicesClient.java:1128)
	at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchConfiguration.createIndex(ElasticsearchConfiguration.java:85)
	at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchIndexer.createIndex(ElasticsearchIndexer.java:298)
	at org.icij.datashare.web.IndexResource.createIndex(IndexResource.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.codestory.http.routes.ReflectionRoute.invoke(ReflectionRoute.java:83)
	at net.codestory.http.routes.ReflectionRoute.lambda$body$0(ReflectionRoute.java:45)
	at net.codestory.http.annotations.MethodAnnotations.apply(MethodAnnotations.java:48)
	at net.codestory.http.routes.ReflectionRoute.body(ReflectionRoute.java:40)
	at net.codestory.http.routes.RouteWithPattern.body(RouteWithPattern.java:56)
	at net.codestory.http.routes.Route.apply(Route.java:25)
	at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$98caf044$1(RouteCollection.java:577)
	at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
	at org.icij.datashare.session.LocalUserFilter.otherUri(LocalUserFilter.java:30)
	at net.codestory.http.filters.auth.CookieAuthFilter.apply(CookieAuthFilter.java:78)
	at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
	at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
	at org.icij.datashare.web.IndexWaiterFilter.apply(IndexWaiterFilter.java:43)
	at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
	at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
	at org.icij.datashare.session.LocalUserFilter.otherUri(LocalUserFilter.java:30)
	at net.codestory.http.filters.auth.CookieAuthFilter.apply(CookieAuthFilter.java:78)
	at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
	at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
	at org.icij.datashare.web.IndexWaiterFilter.apply(IndexWaiterFilter.java:43)
	at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
	at net.codestory.http.routes.RouteCollection.apply(RouteCollection.java:567)
	at net.codestory.http.AbstractWebServer.handleHttp(AbstractWebServer.java:152)
	at net.codestory.http.internal.SimpleServerWrapper.handle(SimpleServerWrapper.java:71)
	at org.simpleframework.http.socket.service.RouterContainer.handle(RouterContainer.java:106)
	at org.simpleframework.http.core.RequestDispatcher.dispatch(RequestDispatcher.java:121)
	at org.simpleframework.http.core.RequestDispatcher.run(RequestDispatcher.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.elasticsearch.client.ResponseException: method [HEAD], host [http://elasticsearch:9200], URI [/local-datashare?include_type_name=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true], status line [HTTP/1.1 400 Bad Request]
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:936)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:233)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1764)
	... 40 common frames omitted
Caused by: org.elasticsearch.client.ResponseException: method [HEAD], host [http://elasticsearch:9200], URI [/local-datashare?include_type_name=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true], status line [HTTP/1.1 400 Bad Request]
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:552)
	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:537)
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:123)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.responseReceived(HttpAsyncRequestExecutor.java:309)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:255)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	... 1 common frames omitted
```

**Comment by annelhote** [comment]
Thank for your feedback ! It should be corrected.
Please try with the last version : `wget https://github.com/ICIJ/datashare-installer/releases/download/8.6.1/datashare.sh`

**Comment by kylemcdonald** [comment]
Thanks! The elasticsearch upgrade fixed it 👌
