### ISSUE TITLE
Old ES uri is still existing in the client

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#755]
**Describe the bug**

When accessing simple search in datashare there is this exception : 

```
2021-02-22 10:15:40,066 [Worker: RequestDispatcher: Thread-30] ERROR Fluent - Unable to GET /api/index/search/local-datashare/doc/a6998346a50e59e41a09fe4fa525ee6fc9602d4319009b17a5d2bbb062bb28ee48e7eb9dd5d1188c0
e699e6ab438744b                                                                                                                                                                                                    
2021-02-22 10:15:40,069 [Worker: RequestDispatcher: Thread-30] ERROR Fluent - Unexpected error:                                                                                                                    
java.lang.IllegalStateException: Unable to apply route                                                                                                                                                             
        at net.codestory.http.routes.ReflectionRoute.lambda$body$0(ReflectionRoute.java:54)                                                                                                                        
        at net.codestory.http.annotations.MethodAnnotations.apply(MethodAnnotations.java:48)                                                                                                                       
        at net.codestory.http.routes.ReflectionRoute.body(ReflectionRoute.java:40)
        at net.codestory.http.routes.RouteWithPattern.body(RouteWithPattern.java:56)
        at net.codestory.http.routes.Route.apply(Route.java:25)
        at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$98caf044$1(RouteCollection.java:577)
        at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
        at org.icij.datashare.session.LocalUserFilter.otherUri(LocalUserFilter.java:30)
        at net.codestory.http.filters.auth.CookieAuthFilter.apply(CookieAuthFilter.java:78)
        at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
        at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
        at org.icij.datashare.web.IndexWaiterFilter.apply(IndexWaiterFilter.java:44)
        at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
        at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
        at org.icij.datashare.mode.CorsFilter.apply(CorsFilter.java:19)
        at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
        at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
        at org.icij.datashare.session.LocalUserFilter.otherUri(LocalUserFilter.java:30)
        at net.codestory.http.filters.auth.CookieAuthFilter.apply(CookieAuthFilter.java:78)
        at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
        at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
        at org.icij.datashare.web.IndexWaiterFilter.apply(IndexWaiterFilter.java:44)
        at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
        at net.codestory.http.routes.RouteCollection.apply(RouteCollection.java:567)
        at net.codestory.http.AbstractWebServer.handleHttp(AbstractWebServer.java:152)
        at net.codestory.http.internal.SimpleServerWrapper.handle(SimpleServerWrapper.java:71)
        at org.simpleframework.http.socket.service.RouterContainer.handle(RouterContainer.java:106)
        at org.simpleframework.http.core.RequestDispatcher.dispatch(RequestDispatcher.java:121)
        at org.simpleframework.http.core.RequestDispatcher.run(RequestDispatcher.java:103)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.elasticsearch.client.ResponseException: method [GET], host [http://elasticsearch:9200], URI [/local-datashare/doc/a6998346a50e59e41a09fe4fa525ee6fc9602d4319009b17a5d2bbb062bb28ee48e7eb9dd5d1188c0e699e6ab438744b?routing=a6998346a50e59e41a09fe4fa525ee6fc9602d4319009b17a5d2bbb062bb28ee48e7eb9dd5d1188c0e699e6ab438744b&_source=contentLength,contentType,path], status line [HTTP/1.1 404 Not Found]
Warnings: [[types removal] Specifying types in document get requests is deprecated, use the /{index}/_doc/{id} endpoint instead.]
{"_index":"local-datashare","_type":"doc","_id":"a6998346a50e59e41a09fe4fa525ee6fc9602d4319009b17a5d2bbb062bb28ee48e7eb9dd5d1188c0e699e6ab438744b","found":false}
        at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:302)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:272)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:246)
```

It seems that old ES urls (before 7) are accessing `/index/_doc/id` url 

**To Reproduce**

I indexed documents then went to the main search to see them.

**Comment by annelhote** [comment]
Hey @bamthomas, I was not able to reproduce your bug, maybe it is linked to the document `a6998346a50e59e41a09fe4fa525ee6fc9602d4319009b17a5d2bbb062bb28ee48e7eb9dd5d1188c0e699e6ab438744b`. Would you send it to me ? thx

**Comment by annelhote** [comment]
I still can't reproduce the error even with the guilty file.

**Comment by bamthomas** [comment]
reset devenv and pull rebuild fixed the error
