### ISSUE TITLE
Downloading of models fails if it lasts > 30s

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#78]
A timeout is interrupting the downloading of models :

    2019-02-13 13:22:58,835 [CORENLP-0] INFO  NlpConsumer - extracting CORENLP entities for document 4c76b7a367c810aa717ec49caf5bd8ee3edeefd197241f6bd3698ed5de2c4ddc
    2019-02-13 13:22:58,835 [CORENLP-0] INFO  CorenlpPipeline - initializing CORENLP ENGLISH [TOKEN, SENTENCE, POS, LEMMA, NER]
    2019-02-13 13:22:58,850 [CORENLP-0] INFO  CoreNlpNerModels - downloading models for language ENGLISH under dist/models/corenlp/3-8-0/en
    2019-02-13 13:23:28,832 [pool-3-thread-1] INFO  NlpApp - consumers have not finished yet, interrupting...
    2019-02-13 13:23:28,833 [CORENLP-0] ERROR CoreNlpNerModels - failed downloading models for ENGLISH
    java.lang.InterruptedException: null
        at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:404)
        at java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at com.amazonaws.services.s3.transfer.internal.MultipleFileTransferMonitor$1.get(MultipleFileTransferMonitor.java:51)
        at com.amazonaws.services.s3.transfer.internal.AbstractTransfer.waitForCompletion(AbstractTransfer.java:100)
        at com.amazonaws.services.s3.transfer.internal.MultipleFileDownloadImpl.waitForCompletion(MultipleFileDownloadImpl.java:76)
        at org.icij.datashare.io.RemoteFiles.download(RemoteFiles.java:65)
        at org.icij.datashare.text.nlp.AbstractModels.downloadIfNecessary(AbstractModels.java:108)
        at org.icij.datashare.text.nlp.AbstractModels.load(AbstractModels.java:60)
        at org.icij.datashare.text.nlp.AbstractModels.get(AbstractModels.java:49)
        at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.initializeNerAnnotator(CorenlpPipeline.java:180)
        at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.initialize(CorenlpPipeline.java:77)
        at org.icij.datashare.text.nlp.NlpConsumer.findNamedEntities(NlpConsumer.java:66)
        at org.icij.datashare.text.nlp.NlpConsumer.run(NlpConsumer.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by bamthomas** [comment]
the fix is just waiting more time (10 mn)
