### ISSUE TITLE
Huge contentTextLength stops indexing

### ISSUE THREAD

**Issue by pirhoo** [ICIJ/datashare#785]
**Describe the bug**

When a document has a huge `contentText` the value of `contextTextLength` is too large for an integer (more than 32 bits):

```
java.lang.NumberFormatException: For input string: "7862117376"
	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at java.base/java.lang.Integer.valueOf(Unknown Source)
	at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchSpewer.getDocumentMap(ElasticsearchSpewer.java:129)
	at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchSpewer.prepareRequest(ElasticsearchSpewer.java:87)
	at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchSpewer.writeDocument(ElasticsearchSpewer.java:63)
	at org.icij.spewer.Spewer.write(Spewer.java:56)
	at org.icij.extract.extractor.Extractor.extract(Extractor.java:266)
	at org.icij.extract.extractor.Extractor.extract(Extractor.java:293)
	at org.icij.extract.extractor.DocumentConsumer.lambda$accept$0(DocumentConsumer.java:124)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Expected behavior**

Datashare should be able to index huge file with a contentTextLength up to 64 bits.

**Comment by bamthomas** [comment]
see 9a031150683de3cd65b618025b1039b463f36e4f
and ICIJ/datashare-client/f37e150180a91b956ee6f7f9be1a218355b54b92
