### ISSUE TITLE
ERROR CoreNlpNerModels: Unable to load NER when analyzing documents.

### ISSUE THREAD

**Issue by dmehrotra** [ICIJ/datashare#795]
**Bug**

Unable to load NER when analyzing documents.

**To Reproduce**

1. Fresh installation of Datashare using the standalone installer.
2. Go to http://localhost:8080/#/indexing
3. Run Text Extraction on PDFs. 
5. Click on Find People Organizations, Locations, and Email Addresses
4. Terminal Output window reads:

`2021-05-05 15:23:11,792 [CORENLP-0] ERROR CoreNlpNerModels - failed loading NER
java.io.IOException: Unable to open "edu/stanford/nlp/models/ner/english.all.3class.caseless.distsim.crf.ser.gz" as class path, filename or URL
	at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:481)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1505)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1497)
	at edu.stanford.nlp.ie.crf.CRFClassifier.getClassifier(CRFClassifier.java:2888)
	at org.icij.datashare.text.nlp.corenlp.models.CoreNlpNerModels.loadModelFile(CoreNlpNerModels.java:75)
	at org.icij.datashare.text.nlp.corenlp.models.CoreNlpNerModels.loadModelFile(CoreNlpNerModels.java:39)
	at org.icij.datashare.text.nlp.AbstractModels.load(AbstractModels.java:59)
	at org.icij.datashare.text.nlp.AbstractModels.get(AbstractModels.java:46)
	at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.processNerClassifier(CorenlpPipeline.java:196)
	at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.process(CorenlpPipeline.java:91)
	at org.icij.datashare.nlp.NlpConsumer.findNamedEntities(NlpConsumer.java:73)
	at org.icij.datashare.nlp.NlpConsumer.call(NlpConsumer.java:43)
	at org.icij.datashare.nlp.NlpConsumer.call(NlpConsumer.java:20)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
"`

**Screenshots**
<img width="931" alt="Screen Shot 2021-05-05 at 3 59 03 PM" src="https://user-images.githubusercontent.com/5003523/117201606-d55b8800-adba-11eb-8c85-10b93e22591b.png">

**Desktop (please complete the following information):**
 - OS: iOS Big Sur 11.2.3
 - Browser: e.g. Chrome

**Additional context**
Thanks
**(Optional) Your contact, availabilities and timezone if a video call with screensharing is needed**
dmehrotra@revealnews.org based in New York (EST)

**Comment by bamthomas** [comment]
hello @dmehrotra could you provide 5 lines before the loading issue ? Thank you.
