### ISSUE TITLE
Exception in the logs : field too long for varchar(96)

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#833]
**Describe the bug**

when looking at the logs I've seen this exception

```
org.jooq.exception.DataAccessException: SQL [insert into "user_history" ("creation_date", "modification_date", "user_id", "type", "prj_id", "name", "uri") values (cast(? as timestamp), cast(? as timestamp), ?, ?, ?, ?, ?) on conflict ("user_id", "uri") do update set "modification_date" = cast(? as timestamp) returning "user_history"."id"]; ERROR: value too long for type character varying(96)
	at org.jooq_3.12.3.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2717)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:755)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:382)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:119)
	at org.icij.datashare.db.JooqRepository.addToHistory(JooqRepository.java:187)
	at org.icij.datashare.web.UserResource.addToHistory(UserResource.java:84)
```

**To Reproduce**

I'm not sure how to reproduce this issue.

**Expected behavior**

No error

**Comment by bamthomas** [comment]
as it is hard to update type for SQLite, I did not make a migration, but directly change the type in the table creation.
