### ISSUE TITLE
Batch search daemon is loosing its connection to redis (via redisson)

### ISSUE THREAD

**Issue by mvanzalu** [ICIJ/datashare#836]
**Describe the bug**
The batch search instances are often frozen leaving all batch searches in 'QUEUED" state.

**Comment by mvanzalu** [comment]
This error message sometimes appears in docker logs :

Exception in thread "main" org.redisson.client.WriteRedisConnectionException: Unable to write command into connection! Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=value:50:queue:0, freeConnectionsAmount=0, freeConnectionsCounter=value:0:queue:0, freezed=false, freezeReason=null, client=[addr=redis://datashare-production.x95ykj.0001.use1.cache.amazonaws.com:6379], nodeType=MASTER, firstFail=0]]], connection: RedisConnection@1868257952 [redisClient=[addr=redis://datashare-production.x95ykj.0001.use1.cache.amazonaws.com:6379], channel=[id: 0x153e9a77, L:/10.137.1.2:48904 ! R:datashare-production.x95ykj.0001.use1.cache.amazonaws.com/172.30.0.106:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@715016a3(incomplete)], command=(BLPOP), params=[ds:batchsearch:queue, 60], codec=org.redisson.client.codec.StringCodec]],
command: (BLPOP), params: [ds:batchsearch:queue, 60] after 0 retry attempts                                                                                                                               
        at org.redisson.command.RedisExecutor.checkWriteFuture(RedisExecutor.java272)                                                                                                                     
        at org.redisson.command.RedisExecutor.access$100(RedisExecutor.java59)                                                                                                                            
        at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java161)                                                                                                                  
        at org.redisson.command.RedisExecutor$1.operationComplete(RedisExecutor.java158)                                                                                                                  
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java577)                                                                                                                
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java570)                                                                                                               
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java549)                                                                                                             
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java490)                                                                                                                
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:993)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:865)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
        at org.redisson.client.handler.CommandEncoder.write(CommandEncoder.java:76)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
        at org.redisson.client.handler.CommandBatchEncoder.write(CommandBatchEncoder.java:45)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
        ...   
Caused by: java.nio.channels.ClosedChannelException
        at io.netty.channel.AbstractChannel$AbstractUnsafe.newClosedChannelException(AbstractChannel.java:957)
        ... 52 more
