### ISSUE TITLE
BatchSearch fails with error 500 from ES

### ISSUE THREAD

**Issue by mvanzalu** [ICIJ/datashare#839]
**Describe the bug**
Some batch searches fail with 500 error from ElasticSearch. It tends to happen when the number of queries is greater than 500 queries.

**To Reproduce**
Steps to reproduce the behavior locally:
Run a batch search with a high number of queries.

**Comment by mvanzalu** [comment]
Error message : 
`
2021-08-25 15:21:12,090 [pool-2-thread-2] ERROR BatchSearchLoop - exception while running batch eb51e6fc-4c3c-4a12-bd94-2f2b7aa47bf7
org.icij.datashare.batch.SearchException: org.elasticsearch.client.ResponseException: method [POST], host [http://elasticsearch:9200], URI [/local-datashare/_search?typed_keys=true&max_concurrent_shard_requests=5&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&ignore_throttled=true&scroll=60000ms&search_type=query_then_fetch&batched_reduce_size=512&ccs_minimize_roundtrips=true], status line [HTTP/1.1 500 Internal Server Error]
{"error":{"root_cause":[{"type":"exception","reason":"Trying to create too many scroll contexts. Must be less than or equal to: [500]. This limit can be set by changing the [search.max_open_scroll_context] setting."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"local-datashare","node":"gsrV0ALxQFC5ExLJlXhbFQ","reason":{"type":"exception","reason":"Trying to create too many scroll contexts. Must be less than or equal to: [500]. This limit can be set by changing the [search.max_open_scroll_context] setting."}}]},"status":500}
        at org.icij.datashare.tasks.BatchSearchRunner.call(BatchSearchRunner.java:111)
        at org.icij.datashare.tasks.BatchSearchLoop.run(BatchSearchLoop.java:65)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.elasticsearch.client.ResponseException: method [POST], host [http://elasticsearch:9200], URI [/local-datashare/_search?typed_keys=true&max_concurrent_shard_requests=5&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&ignore_throttled=true&scroll=60000ms&search_type=query_then_fetch&batched_reduce_size=512&ccs_minimize_roundtrips=true], status line [HTTP/1.1 500 Internal Server Error]
{"error":{"root_cause":[{"type":"exception","reason":"Trying to create too many scroll contexts. Must be less than or equal to: [500]. This limit can be set by changing the [search.max_open_scroll_context] setting."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"local-datashare","node":"gsrV0ALxQFC5ExLJlXhbFQ","reason":{"type":"exception","reason":"Trying to create too many scroll contexts. Must be less than or equal to: [500]. This limit can be set by changing the [search.max_open_scroll_context] setting."}}]},"status":500}
        at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
        at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1632)
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1602)
        at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1572)
        at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1088)
        at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchIndexer$ElasticsearchSearcher.scroll(ElasticsearchIndexer.java:392)
        at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchIndexer$ElasticsearchSearcher.scroll(ElasticsearchIndexer.java:380)
        at org.icij.datashare.tasks.BatchSearchRunner.call(BatchSearchRunner.java:91)
        ... 8 common frames omitted
2021-08-25 15:21:12,146 [pool-2-thread-2] WARN  BatchSearchLoop - batch search eb51e6fc-4c3c-4a12-bd94-2f2b7aa47bf7 not ran because in state FAILURE
2021-08-25 15:21:12,146 [pool-2-thread-2] INFO  BatchSearchLoop - exiting main loop

`
