### ISSUE TITLE
CoreNLP enabling of extra models fails?

### ISSUE THREAD

**Issue by DrWhax** [ICIJ/datashare#84]
Hey!

Thanks for working on Datashare! I've been toying with it for the past few days and came across some problems.

When choosing CoreNLP and running the extraction, I run into the following issue. I'm using Debian 9 Stretch with Docker.

```
2019-02-21 12:49:03,506 [CORENLP-0] INFO  CorenlpPipeline - name-finding for SPANISH
2019-02-21 12:49:03,509 [CORENLP-0] INFO  CoreNlpNerModels - downloading models for language SPANISH under dist/models/corenlp/3-8-0/es
2019-02-21 12:49:08,027 [CORENLP-0] INFO  CoreNlpNerModels - models successfully downloaded for language SPANISH
2019-02-21 12:49:08,027 [CORENLP-0] INFO  CoreNlpNerModels - adding models/corenlp/3-8-0/es/stanford-corenlp-3.8.0-models-spanish.jar to system classloader
2019-02-21 12:49:08,028 [CORENLP-0] ERROR CoreNlpNerModels - failed loading NER
java.io.IOException: Unable to open "edu/stanford/nlp/models/ner/spanish.ancora.distsim.s512.crf.ser.gz" as class path, filename or URL
	at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:480)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1498)
	at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1490)
	at edu.stanford.nlp.ie.crf.CRFClassifier.getClassifier(CRFClassifier.java:2934)
	at org.icij.datashare.text.nlp.corenlp.models.CoreNlpNerModels.loadModelFile(CoreNlpNerModels.java:75)
	at org.icij.datashare.text.nlp.corenlp.models.CoreNlpNerModels.loadModelFile(CoreNlpNerModels.java:39)
	at org.icij.datashare.text.nlp.AbstractModels.load(AbstractModels.java:62)
	at org.icij.datashare.text.nlp.AbstractModels.get(AbstractModels.java:49)
	at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.processNerClassifier(CorenlpPipeline.java:197)
	at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.process(CorenlpPipeline.java:92)
	at org.icij.datashare.text.nlp.NlpConsumer.findNamedEntities(NlpConsumer.java:67)
	at org.icij.datashare.text.nlp.NlpConsumer.run(NlpConsumer.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-02-21 12:49:08,028 [CORENLP-0] WARN  NlpConsumer - error in consumer main loop
java.lang.NullPointerException: null
	at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.processNerClassifier(CorenlpPipeline.java:198)
	at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.process(CorenlpPipeline.java:92)
	at org.icij.datashare.text.nlp.NlpConsumer.findNamedEntities(NlpConsumer.java:67)
	at org.icij.datashare.text.nlp.NlpConsumer.run(NlpConsumer.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I guess it's loads the correct jar for Spanish but it fails to load "edu/stanford/nlp/models/ner/spanish.ancora.distsim.s512.crf.ser.gz". Not sure how relevant it is.

Happy to test any patches!

**Comment by bamthomas** [comment]
yes I reproduce it with a spanish document. It seems that it is related to the spanish models for core NLP. I'm looking after it.

**Comment by bamthomas** [comment]
We've seen that stanford released core NLP pipeline in 3.9.2 so we upgraded the library. I've tested it on spanish and it seems to work properly.

**Comment by DrWhax** [comment]
This has indeed fixed the issue! Thanks!

**Comment by bamthomas** [comment]
Thank you for your feedback @DrWhax

**Comment by CanYouGiveMeAName** [comment]
java.io.IOException: Unable to open "data/model/ner/spanish.ancora.distsim.s512.crf.ser.gz" as class path, filename or URL
....
Exception in thread "main" edu.stanford.nlp.io.RuntimeIOException: java.io.IOException: Couldn't load classifier from data/model/ner/spanish.ancora.distsim.s512.crf.ser.gz

but i meet the problem again.
and i download on: https://stanfordnlp.github.io/CoreNLP/index.html#download
version: 3.9.2
