### ISSUE TITLE
java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED

### ISSUE THREAD

**Issue by bamthomas** [ICIJ/datashare#855]
**Describe the bug**

Yesterday datashare was blocked with the error mentioned in the title that caused a HTTP 500 response.

**To Reproduce**

We don't know how to reproduce 

I restarted the two servers.

I'm creating the issue in case it happens again, to gather information.

**Comment by bamthomas** [comment]
the execution context was : 

```
java.lang.RuntimeException: Request cannot be executed; I/O reactor status: STOPPED
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:887)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:283)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1632)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1617)
	at org.elasticsearch.client.RestHighLevelClient.ping(RestHighLevelClient.java:775)
	at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchIndexer.getHealth(ElasticsearchIndexer.java:337)
	at org.icij.datashare.web.StatusResource.getStatus(StatusResource.java:59)
	at jdk.internal.reflect.GeneratedMethodAccessor233.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.codestory.http.routes.ReflectionRoute.invoke(ReflectionRoute.java:83)
```
So it was the monitoring that was calling getStatus in that case but it was blocking every HTTP request on the fluent-http server.

It is maybe related to : 
https://stackoverflow.com/questions/35350376/java-lang-illegalstateexception-request-cannot-be-executed-i-o-reactor-status

**Comment by bamthomas** [comment]
new occurence of the same pb this morning.

I did 
```shell
$ sudo netstat -laputen
# nothing special white few connections
$ htop 
# no swap, memory 19GB free, no CPU 
$ grep -E 'WARN|ERROR' /var/log/syslog
# no error lines
``` 

so the machine seems to be OK AFAIK.

**Comment by bamthomas** [comment]
It happened once again this morning. Actually datashare was working ok but the url [`/api/index/search`](https://github.com/ICIJ/datashare/wiki/Backend-%E2%80%BA-API#post__api_index_search__path_) was generating a `Request cannot be executed; I/O reactor status: STOPPED` error.

Looking a bit more with CD, we found that it may be related to this issue : 
https://github.com/elastic/elasticsearch/issues/42133

Which has been fixed with [this workaround](https://github.com/elastic/elasticsearch/issues/42133#issuecomment-923008816) resetting the client when it is not detected has running anymore.
