### ISSUE TITLE
Apache Tika error is thrown when embedded image in documents can't be parsed

### ISSUE THREAD

**Issue by DrWhax** [ICIJ/datashare#87]
```
2019-02-26 22:22:40,080 [Apache Tika: XXX.doc] ERROR EmbedParser - Unable to parse embedded document: "image2" (image/unknown) (in "/home/datashare/data/XXX.doc").
org.apache.tika.exception.ZeroByteFileException: InputStream must have > 0 bytes
        at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:122)
        at org.apache.tika.parser.ParserDecorator.parse(ParserDecorator.java:188)
        at org.apache.tika.parser.DigestingParser.parse(DigestingParser.java:84)
        at org.apache.tika.parser.DelegatingParser.parse(DelegatingParser.java:72)
        at org.icij.extract.extractor.EmbedParser.delegateParsing(EmbedParser.java:76)
        at org.icij.extract.extractor.EmbedSpawner.spawnEmbedded(EmbedSpawner.java:114)
        at org.icij.extract.extractor.EmbedSpawner.parseEmbedded(EmbedSpawner.java:63)
        at org.apache.tika.extractor.EmbeddedDocumentUtil.parseEmbedded(EmbeddedDocumentUtil.java:220)
        at org.apache.tika.parser.microsoft.AbstractPOIFSExtractor.handleEmbeddedResource(AbstractPOIFSExtractor.java:124)
        at org.apache.tika.parser.microsoft.AbstractPOIFSExtractor.handleEmbeddedResource(AbstractPOIFSExtractor.java:100)
        at org.apache.tika.parser.microsoft.WordExtractor.handlePictureCharacterRun(WordExtractor.java:640)
        at org.apache.tika.parser.microsoft.WordExtractor.handleSpecialCharacterRuns(WordExtractor.java:543)
        at org.apache.tika.parser.microsoft.WordExtractor.handleParagraph(WordExtractor.java:359)
        at org.apache.tika.parser.microsoft.WordExtractor.handleParagraph(WordExtractor.java:286)
        at org.apache.tika.parser.microsoft.WordExtractor.parse(WordExtractor.java:189)
        at org.apache.tika.parser.microsoft.OfficeParser.parse(OfficeParser.java:176)
        at org.apache.tika.parser.microsoft.OfficeParser.parse(OfficeParser.java:132)
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
        at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143)
        at org.apache.tika.parser.ParserDecorator.parse(ParserDecorator.java:188)
        at org.apache.tika.parser.DigestingParser.parse(DigestingParser.java:84)
        at org.apache.tika.parser.ParsingReader$ParsingTask.run(ParsingReader.java:235)
        at java.lang.Thread.run(Thread.java:748)
```

This happens in .doc and .docx, I can't remember if it's also PDF.

**Comment by bamthomas** [comment]
yes it is thrown by tika and catched by extract. This is a log indicating that there has been an issue on the image parsing, but it doesn't break the main document parsing with its others children :

* TikaException is caught here : https://github.com/ICIJ/extract/blob/d57943c019c84ba64fde5dda0931ab14c60508ad/extract-lib/src/main/java/org/icij/extract/extractor/EmbedParser.java#L82
* global Exception here : https://github.com/ICIJ/extract/blob/d57943c019c84ba64fde5dda0931ab14c60508ad/extract-lib/src/main/java/org/icij/extract/extractor/EmbedSpawner.java#L115

**Comment by damossb** [comment]
I have the same problem and fail to solve or circumvent it. I tried to increase the value for "TesseractOCRParser timeout", but this didn't work. Any ideas to circumvent it? 

I have a dataset of PDF documents that require OCR and almost every page is not processed due to this thrown exception.

The error looks as follows:

`2026-05-21 09:44:26,807 [Apache Tika: XXX.pdf] ERROR EmbedParser - Unable to parse embedded document: "image3.jpg" (image/jpeg) (in "/home/datashare/data/XXX/XXX.pdf - XXX.pdf").`

**Comment by pirhoo** [comment]
Hi @damossb, what version of Datashare do you use? There was a lot changes lately on the Tika Parser and version.

**Comment by damossb** [comment]
Hi!

I am currently using Datashare version 21.2.2 (running in Docker server mode).

The main issue I'm encountering is a consistent TesseractOCRParser timeout when processing PDFs created by mobile scanning apps (like CamScanner). These documents seem to require more processing time due to noise/artifacts.

(To rule out resource starvation: I am running this on a hardware with 64 GB of physical RAM. I have allocated 16 GB of heap memory specifically to the Datashare container (-Xmx16g) and another 32 GB to Elasticsearch. The CPU load is stable, and there is no swapping occurring.)

I noticed that the timeout triggers every 60 seconds. I tried to increase this limit using both a datashare.properties file and a custom tika-config.xml (overriding the TesseractOCRParser timeout parameter), but the limit remained enforced in the logs. It seems like the EmbedParser or the underlying Tika bridge doesn't pick up the custom timeout settings for embedded images within the PDF.

**Comment by pirhoo** [comment]
Interesting, thanks for the detailed answer. @mvanzalu does that give you any hint on how to solve this?

**Comment by mvanzalu** [comment]
Thank you @damossb for the breakdown, I think we can reopen the issue so we can have a closer look on it.

**Comment by fl02** [comment]
Can confirm, though it seems not to be limited to mobile scanning apps but scanning apps in general. My DS version is  21.0.7 running on Podman. Below is an excerpt from the error log:

> 2026-06-04 09:47:26,601 [Apache Tika: ....pdf] ERROR EmbedParser - Unable to parse embedded document: "image71.tif" (image/tiff) (in "...pdf").
org.apache.tika.exception.TikaException: TesseractOCRParser timeout
	at org.apache.tika.parser.ocr.TesseractOCRParser.runOCRProcess(TesseractOCRParser.java:474)
	at org.apache.tika.parser.ocr.TesseractOCRParser.doOCR(TesseractOCRParser.java:447)
	at org.apache.tika.parser.ocr.TesseractOCRParser.parse(TesseractOCRParser.java:334)
	at org.apache.tika.parser.ocr.TesseractOCRParser.parse(TesseractOCRParser.java:276)
	at org.icij.extract.ocr.OCRParserAdapter.parse(OCRParserAdapter.java:33)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:204)
	at org.apache.tika.parser.ParserDecorator.parse(ParserDecorator.java:153)
	at org.apache.tika.parser.DigestingParser.parse(DigestingParser.java:57)
	at org.apache.tika.parser.image.AbstractImageParser.parse(AbstractImageParser.java:106)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:204)
	at org.apache.tika.parser.ParserDecorator.parse(ParserDecorator.java:153)
	at org.apache.tika.parser.DigestingParser.parse(DigestingParser.java:57)
	at org.apache.tika.parser.DelegatingParser.parse(DelegatingParser.java:71)
	at org.icij.extract.extractor.EmbedParser.delegateParsing(EmbedParser.java:80)
	at org.icij.extract.extractor.EmbedSpawner.parseEmbedded(EmbedSpawner.java:58)
	at org.apache.tika.parser.pdf.image.ImageGraphicsEngine.processImage(ImageGraphicsEngine.java:434)
	at org.apache.tika.parser.pdf.image.ImageGraphicsEngine.drawImage(ImageGraphicsEngine.java:290)
	at org.apache.pdfbox.contentstream.operator.graphics.DrawObject.process(DrawObject.java:78)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:919)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:552)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:510)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:157)
	at org.apache.tika.parser.pdf.image.ImageGraphicsEngine.run(ImageGraphicsEngine.java:235)
	at org.apache.tika.parser.pdf.PDF2XHTML.extractImages(PDF2XHTML.java:203)
	at org.apache.tika.parser.pdf.PDF2XHTML.endPage(PDF2XHTML.java:148)
	at org.apache.pdfbox.text.PDFTextStripper.processPage(PDFTextStripper.java:381)
	at org.apache.tika.parser.pdf.PDF2XHTML.processPage(PDF2XHTML.java:136)
	at org.apache.tika.parser.pdf.AbstractPDF2XHTML.processPages(AbstractPDF2XHTML.java:1362)
	at org.apache.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:252)
	at org.apache.tika.parser.pdf.PDF2XHTML.process(PDF2XHTML.java:107)
	at org.apache.tika.parser.pdf.PDFParser.parse(PDFParser.java:219)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:204)
	at org.apache.tika.parser.ParserDecorator.parse(ParserDecorator.java:153)
	at org.apache.tika.parser.DigestingParser.parse(DigestingParser.java:57)
	at org.icij.extract.parser.ParsingReaderWithContentHandler$ParsingTask.run(ParsingReaderWithContentHandler.java:279)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2026-06-04 09:47:26,639 [Apache Tika: ....pdf] ERROR EmbedParser - Unable to parse embedded document: "image91.tif" (image/tiff) (in "...pdf - ....pdf").
org.apache.tika.exception.TikaException: TesseractOCRParser timeout
	at org.apache.tika.parser.ocr.TesseractOCRParser.runOCRProcess(TesseractOCRParser.java:474)
	at org.apache.tika.parser.ocr.TesseractOCRParser.doOCR(TesseractOCRParser.java:447)
	at org.apache.tika.parser.ocr.TesseractOCRParser.parse(TesseractOCRParser.java:334)
	at org.apache.tika.parser.ocr.TesseractOCRParser.parse(TesseractOCRParser.java:276)
	at org.icij.extract.ocr.OCRParserAdapter.parse(OCRParserAdapter.java:33)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:204)
	at org.apache.tika.parser.ParserDecorator.parse(ParserDecorator.java:153)
	at org.apache.tika.parser.DigestingParser.parse(DigestingParser.java:57)
	at org.apache.tika.parser.image.AbstractImageParser.parse(AbstractImageParser.java:106)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:204)
	at org.apache.tika.parser.ParserDecorator.parse(ParserDecorator.java:153)
	at org.apache.tika.parser.DigestingParser.parse(DigestingParser.java:57)
	at org.apache.tika.parser.DelegatingParser.parse(DelegatingParser.java:71)
	at org.icij.extract.extractor.EmbedParser.delegateParsing(EmbedParser.java:80)
	at org.icij.extract.extractor.EmbedSpawner.parseEmbedded(EmbedSpawner.java:58)
	at org.apache.tika.parser.pdf.image.ImageGraphicsEngine.processImage(ImageGraphicsEngine.java:434)
	at org.apache.tika.parser.pdf.image.ImageGraphicsEngine.drawImage(ImageGraphicsEngine.java:290)
	at org.apache.pdfbox.contentstream.operator.graphics.DrawObject.process(DrawObject.java:78)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:919)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:552)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:510)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:157)
	at org.apache.tika.parser.pdf.image.ImageGraphicsEngine.run(ImageGraphicsEngine.java:235)
	at org.apache.tika.parser.pdf.PDF2XHTML.extractImages(PDF2XHTML.java:203)
	at org.apache.tika.parser.pdf.PDF2XHTML.endPage(PDF2XHTML.java:148)
	at org.apache.pdfbox.text.PDFTextStripper.processPage(PDFTextStripper.java:381)
	at org.apache.tika.parser.pdf.PDF2XHTML.processPage(PDF2XHTML.java:136)
	at org.apache.tika.parser.pdf.AbstractPDF2XHTML.processPages(AbstractPDF2XHTML.java:1362)
	at org.apache.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:252)
	at org.apache.tika.parser.pdf.PDF2XHTML.process(PDF2XHTML.java:107)
	at org.apache.tika.parser.pdf.PDFParser.parse(PDFParser.java:219)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:204)
	at org.apache.tika.parser.ParserDecorator.parse(ParserDecorator.java:153)
	at org.apache.tika.parser.DigestingParser.parse(DigestingParser.java:57)
	at org.icij.extract.parser.ParsingReaderWithContentHandler$ParsingTask.run(ParsingReaderWithContentHandler.java:279)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2026-06-04 09:48:19,583 [Apache Tika: ....pdf] ERROR EmbedParser - Unable to parse embedded document: "image81.jpg" (image/jpeg) (in "....pdf").
org.apache.tika.exception.TikaException: TesseractOCRParser timeout
	at org.apache.tika.parser.ocr.TesseractOCRParser.runOCRProcess(TesseractOCRParser.java:474)
	at org.apache.tika.parser.ocr.TesseractOCRParser.doOCR(TesseractOCRParser.java:447)
	at org.apache.tika.parser.ocr.TesseractOCRParser.parse(TesseractOCRParser.java:334)
	at org.apache.tika.parser.ocr.TesseractOCRParser.parse(TesseractOCRParser.java:276)
	at org.icij.extract.ocr.OCRParserAdapter.parse(OCRParserAdapter.java:33)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:204)
	at org.apache.tika.parser.ParserDecorator.parse(ParserDecorator.java:153)
	at org.apache.tika.parser.DigestingParser.parse(DigestingParser.java:57)
	at org.apache.tika.parser.image.AbstractImageParser.parse(AbstractImageParser.java:106)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:204)
	at org.apache.tika.parser.ParserDecorator.parse(ParserDecorator.java:153)
	at org.apache.tika.parser.DigestingParser.parse(DigestingParser.java:57)
	at org.apache.tika.parser.DelegatingParser.parse(DelegatingParser.java:71)
	at org.icij.extract.extractor.EmbedParser.delegateParsing(EmbedParser.java:80)
	at org.icij.extract.extractor.EmbedSpawner.parseEmbedded(EmbedSpawner.java:58)
	at org.apache.tika.parser.pdf.image.ImageGraphicsEngine.processImage(ImageGraphicsEngine.java:434)
	at org.apache.tika.parser.pdf.image.ImageGraphicsEngine.drawImage(ImageGraphicsEngine.java:290)
	at org.apache.pdfbox.contentstream.operator.graphics.DrawObject.process(DrawObject.java:78)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:919)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:552)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:510)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:157)
	at org.apache.tika.parser.pdf.image.ImageGraphicsEngine.run(ImageGraphicsEngine.java:235)
	at org.apache.tika.parser.pdf.PDF2XHTML.extractImages(PDF2XHTML.java:203)
	at org.apache.tika.parser.pdf.PDF2XHTML.endPage(PDF2XHTML.java:148)
	at org.apache.pdfbox.text.PDFTextStripper.processPage(PDFTextStripper.java:381)
	at org.apache.tika.parser.pdf.PDF2XHTML.processPage(PDF2XHTML.java:136)
	at org.apache.tika.parser.pdf.AbstractPDF2XHTML.processPages(AbstractPDF2XHTML.java:1362)
	at org.apache.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:252)
	at org.apache.tika.parser.pdf.PDF2XHTML.process(PDF2XHTML.java:107)
	at org.apache.tika.parser.pdf.PDFParser.parse(PDFParser.java:219)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:204)
	at org.apache.tika.parser.ParserDecorator.parse(ParserDecorator.java:153)
	at org.apache.tika.parser.DigestingParser.parse(DigestingParser.java:57)
	at org.icij.extract.parser.ParsingReaderWithContentHandler$ParsingTask.run(ParsingReaderWithContentHandler.java:279)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2026-06-04 09:49:27,384 [Apache Tika: ....pdf] ERROR EmbedParser - Unable to parse embedded document: "image56.tif" (image/tiff) (in "...").
org.apache.tika.exception.TikaException: TesseractOCRParser timeout
	at org.apache.tika.parser.ocr.TesseractOCRParser.runOCRProcess(TesseractOCRParser.java:474)
	at org.apache.tika.parser.ocr.TesseractOCRParser.doOCR(TesseractOCRParser.java:447)
	at org.apache.tika.parser.ocr.TesseractOCRParser.parse(TesseractOCRParser.java:334)
	at org.apache.tika.parser.ocr.TesseractOCRParser.parse(TesseractOCRParser.java:276)
	at org.icij.extract.ocr.OCRParserAdapter.parse(OCRParserAdapter.java:33)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:204)
	at org.apache.tika.parser.ParserDecorator.parse(ParserDecorator.java:153)
	at org.apache.tika.parser.DigestingParser.parse(DigestingParser.java:57)
	at org.apache.tika.parser.image.AbstractImageParser.parse(AbstractImageParser.java:106)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:204)
	at org.apache.tika.parser.ParserDecorator.parse(ParserDecorator.java:153)
	at org.apache.tika.parser.DigestingParser.parse(DigestingParser.java:57)
	at org.apache.tika.parser.DelegatingParser.parse(DelegatingParser.java:71)
	at org.icij.extract.extractor.EmbedParser.delegateParsing(EmbedParser.java:80)
	at org.icij.extract.extractor.EmbedSpawner.parseEmbedded(EmbedSpawner.java:58)
	at org.apache.tika.parser.pdf.image.ImageGraphicsEngine.processImage(ImageGraphicsEngine.java:434)
	at org.apache.tika.parser.pdf.image.ImageGraphicsEngine.drawImage(ImageGraphicsEngine.java:290)
	at org.apache.pdfbox.contentstream.operator.graphics.DrawObject.process(DrawObject.java:78)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:919)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:552)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:510)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:157)
	at org.apache.tika.parser.pdf.image.ImageGraphicsEngine.run(ImageGraphicsEngine.java:235)
	at org.apache.tika.parser.pdf.PDF2XHTML.extractImages(PDF2XHTML.java:203)
	at org.apache.tika.parser.pdf.PDF2XHTML.endPage(PDF2XHTML.java:148)
	at org.apache.pdfbox.text.PDFTextStripper.processPage(PDFTextStripper.java:381)
	at org.apache.tika.parser.pdf.PDF2XHTML.processPage(PDF2XHTML.java:136)
	at org.apache.tika.parser.pdf.AbstractPDF2XHTML.processPages(AbstractPDF2XHTML.java:1362)
	at org.apache.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:252)
	at org.apache.tika.parser.pdf.PDF2XHTML.process(PDF2XHTML.java:107)
	at org.apache.tika.parser.pdf.PDFParser.parse(PDFParser.java:219)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:204)
	at org.apache.tika.parser.ParserDecorator.parse(ParserDecorator.java:153)
	at org.apache.tika.parser.DigestingParser.parse(DigestingParser.java:57)
	at org.icij.extract.parser.ParsingReaderWithContentHandler$ParsingTask.run(ParsingReaderWithContentHandler.java:279)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by bamthomas** [comment]
@fl02 the above commit is adding an ` ocrTimeout`  setting that will be passed to extract. 
You can tweak this parameter to you need.

Besides this, a lot of improvements have been done lately in extract to improve content indexing and avoid skipping files when there are errors.
