### ISSUE TITLE
CoreNLP German 

### ISSUE THREAD

**Issue by DrWhax** [ICIJ/datashare#89]
I encountered this issue, seems related to #84 but instead for the German language.

Version 1.45 on Linux + Docker.

```
2019-03-04 13:39:47,220 [CORENLP-0] ERROR CoreNlpNerModels - failed loading NER
java.io.IOException: Unable to open "edu/stanford/nlp/models/ner/german.conll.hgc_175m_600.crf.ser.gz" as class path, filename or URL
        at edu.stanford.nlp.io.IOUtils.getInputStreamFromURLOrClasspathOrFileSystem(IOUtils.java:480)
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1503)
        at edu.stanford.nlp.ie.AbstractSequenceClassifier.loadClassifier(AbstractSequenceClassifier.java:1495)
        at edu.stanford.nlp.ie.crf.CRFClassifier.getClassifier(CRFClassifier.java:2932)
        at org.icij.datashare.text.nlp.corenlp.models.CoreNlpNerModels.loadModelFile(CoreNlpNerModels.java:75)
        at org.icij.datashare.text.nlp.corenlp.models.CoreNlpNerModels.loadModelFile(CoreNlpNerModels.java:39)
        at org.icij.datashare.text.nlp.AbstractModels.load(AbstractModels.java:62)
        at org.icij.datashare.text.nlp.AbstractModels.get(AbstractModels.java:49)
        at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.initializeNerAnnotator(CorenlpPipeline.java:180)
        at org.icij.datashare.text.nlp.corenlp.CorenlpPipeline.initialize(CorenlpPipeline.java:77)
        at org.icij.datashare.text.nlp.NlpConsumer.findNamedEntities(NlpConsumer.java:66)
        at org.icij.datashare.text.nlp.NlpConsumer.run(NlpConsumer.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-03-04 13:39:47,221 [CORENLP-0] INFO  CorenlpPipeline - name-finding for GERMAN
```

**Comment by Soliine** [comment]
Thanks a lot for this issue as well which seems related to #84 indeed. We'll be investigating next week about this and will provide you with our findings.

**Comment by DrWhax** [comment]
No worries, thanks for acknowledging the ticket and all the hard work, it's been really nice to work with Datashare so far!

**Comment by Soliine** [comment]
See: https://github.com/ICIJ/datashare/issues/146
