### ISSUE TITLE
Search Failure 

### ISSUE THREAD

**Issue by wagnerpaul** [ICIJ/datashare#897]
**Describe the bug**
Unable to search any term if it is not scoped to a specific field

**To Reproduce**
Type in any generic search in the search bar with no scoping. 
Behavior disappears if you you add any scoping either with the selector on the right or with lucine syntax

**Expected behavior**
Some documents returned in the search.  Instead I see "The server encountered a problem"

**Screenshots**

Here is an example of a search that is scoped to "contentType."  It seems to work fine
![Screen Shot 2022-05-10 at 1 55 12 PM](https://user-images.githubusercontent.com/1899971/167721362-a05076d4-cee2-4998-b70a-e62080900b21.png)

Here is an un-scoped search that causes the error.
![Screen Shot 2022-05-10 at 2 06 46 PM](https://user-images.githubusercontent.com/1899971/167721933-627731b0-6ea5-49b3-b143-b3d4a660f95e.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7 
 - Docker: Desktop - 2.3.0.3, Engine - 19.03.8 
 - Datashare: 10.3.0 for docker
 - Browser: Chrome
 - Version: 100.0.4896.127

**Additional context**
I'm pretty sure it has to do with this:
https://discuss.elastic.co/t/field-expansion-for-matches-too-many-fields-limit-1024-got-1998/279168

Logfile entry from Datashare docker instance:

2022-05-10 21:06:01,478 [Worker: RequestDispatcher: Thread-31] ERROR Fluent - Unable to POST /api/index/search/local-datashare/_search
2022-05-10 21:06:01,479 [Worker: RequestDispatcher: Thread-31] ERROR Fluent - Unexpected error:
java.lang.IllegalStateException: Unable to apply route
	at net.codestory.http.routes.ReflectionRoute.lambda$body$0(ReflectionRoute.java:54)
	at net.codestory.http.annotations.MethodAnnotations.apply(MethodAnnotations.java:48)
	at net.codestory.http.routes.ReflectionRoute.body(ReflectionRoute.java:40)
	at net.codestory.http.routes.RouteWithPattern.body(RouteWithPattern.java:56)
	at net.codestory.http.routes.Route.apply(Route.java:25)
	at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$98caf044$1(RouteCollection.java:577)
	at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
	at org.icij.datashare.session.LocalUserFilter.otherUri(LocalUserFilter.java:30)
	at net.codestory.http.filters.auth.CookieAuthFilter.apply(CookieAuthFilter.java:78)
	at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
	at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
	at org.icij.datashare.web.IndexWaiterFilter.apply(IndexWaiterFilter.java:44)
	at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
	at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
	at org.icij.datashare.session.LocalUserFilter.otherUri(LocalUserFilter.java:30)
	at net.codestory.http.filters.auth.CookieAuthFilter.apply(CookieAuthFilter.java:78)
	at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
	at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
	at org.icij.datashare.web.IndexWaiterFilter.apply(IndexWaiterFilter.java:44)
	at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
	at net.codestory.http.routes.RouteCollection.apply(RouteCollection.java:567)
	at net.codestory.http.AbstractWebServer.handleHttp(AbstractWebServer.java:152)
	at net.codestory.http.internal.SimpleServerWrapper.handle(SimpleServerWrapper.java:71)
	at org.simpleframework.http.socket.service.RouterContainer.handle(RouterContainer.java:106)
	at org.simpleframework.http.core.RequestDispatcher.dispatch(RequestDispatcher.java:121)
	at org.simpleframework.http.core.RequestDispatcher.run(RequestDispatcher.java:103)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.elasticsearch.client.ResponseException: method [POST], host [http://elasticsearch:9200], URI [/local-datashare/_search], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to create query: field expansion for [*] matches too many fields, limit: 1024, got: 3994","index_uuid":"nsPvbq6KRQWjftht3vWweQ","index":"local-datashare"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"local-datashare","node":"nvN3IIlTS22HrOgN8k1Faw","reason":{"type":"query_shard_exception","reason":"failed to create query: field expansion for [*] matches too many fields, limit: 1024, got: 3994","index_uuid":"nsPvbq6KRQWjftht3vWweQ","index":"local-datashare","caused_by":{"type":"illegal_argument_exception","reason":"field expansion for [*] matches too many fields, limit: 1024, got: 3994"}}}]},"status":400}
	at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
	at org.icij.datashare.text.indexing.elasticsearch.ElasticsearchIndexer.executeRaw(ElasticsearchIndexer.java:152)
	at org.icij.datashare.web.IndexResource.esPost(IndexResource.java:86)
	at jdk.internal.reflect.GeneratedMethodAccessor272.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.codestory.http.routes.ReflectionRoute.invoke(ReflectionRoute.java:83)
	at net.codestory.http.routes.ReflectionRoute.lambda$body$0(ReflectionRoute.java:45)
	... 28 common frames omitted

**Comment by mvanzalu** [comment]
Hello @wagnerpaul,actually this error is related to this [issue](https://github.com/ICIJ/datashare/issues/818) which has been fixed recently. Unfortunately this is not retroactive so here's a workaround : 

- Create a settings.json which contains : 
`{
  "index": {
    "query": {
      "default_field": [
        "content",
        "content_translated",
        "metadata.tika_metadata_author",
        "metadata.tika_metadata_creator",
        "metadata.tika_metadata_dc_creator",
        "metadata.tika_metadata_dc_title",
        "metadata.tika_metadata_message_from",
        "metadata.tika_metadata_message_to",
        "metadata.tika_metadata_meta_author",
        "metadata.tika_metadata_subject",
        "metadata.tika_metadata_title",
        "name",
        "path",
        "tags"
      ]
    }
  }
}
`
- Push it to ES with this command : `curl -XPUT http://your-elasticsearch-address/_all/_settings -H 'Content-Type: application/json' -d @settings.json`
