### ISSUE TITLE
Using Datashare with NAS Synology DS420+

### ISSUE THREAD

**Issue by Hermano123** [ICIJ/datashare#984]
Dear all,

Thanks for the Datashare solution.
It is a great tool that I would like to use in order to access all my document in one place.
Knowing that, I choose to install DataShare on a Windows Laptop and all my files on a Synology NAS DS420+ in RAID5.

Strange things is that elasticsearch index seems like to be broken...
When trying to analyse/add documents then execute, I have two lines :

    first one is ScanTask
    second one is IndexTask

Index final status is done but I think it is incomplete
ScanTask just freeze after a few minutes I have around 60K files to add but only 40.1K are on Datashare.

Regarding the logs, the following issue is shown :
[Worker: RequestDispatcher:Thread-29] ERROR Fluent - Unexpected error:
java.lang.IllegalArgumentException : cannot add a file (C:\Users\...) outside this directory (C:\Users\...)
at org.icij.datashare.file.DirectoryReport.add(DirectoryReport.java:18)
at org.icij.datashare.file.FileReportVisitor.visitFile(FileReportVisitor.java:23)
at org.icij.datashare.file.FileReportVisitor.visitFile(FileReportVisitor.java:10)
at java.nio.file.Files.walkFileTree(Files.java:2670)
at java.nio.file.Files.walkFileTree(Files.java:2742)
at org.icij.datashare.web.TreeResource.tree(TreeResource.java:60)
at org.icij.datashare.web.TreeResource.getTree(TreeResource.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at net.codestory.http.routes.ReflectionRoute.invoke(ReflectionRoute.java:83)
at net.codestory.http.routes.ReflectionRoute.lambda$body$0(ReflectionRoute.java:45)
at net.codestory.http.annotations.MethodAnnotations.apply(MethodAnnotations.java:48)
at net.codestory.http.routes.ReflectionRoute.body(ReflectionRoute.java:40)
at net.codestory.http.routes.RouteWithPattern.body(RouteWithPattern.java:56)
at net.codestory.http.routes.Route.apply(Route.java:25)
at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$98caf044$1(RouteCollection.java:577)
at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
at org.icij.datashare.session.LocalUserFilter.otherUri(LocalUserFilter.java:30)
at net.codestory.http.filters.auth.CookieAuthFilter.apply(CookieAuthFilter.java:78)
at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
at org.icij.datashare.web.IndexWaiterFilter.apply(IndexWaiterFilter.java:44)
at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
at org.icij.datashare.session.LocalUserFilter.otherUri(LocalUserFilter.java:30)
at net.codestory.http.filters.auth.CookieAuthFilter.apply(CookieAuthFilter.java:78)
at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
at net.codestory.http.routes.RouteCollection.lambda$null$2339cd96$1(RouteCollection.java:593)
at org.icij.datashare.web.IndexWaiterFilter.apply(IndexWaiterFilter.java:44)
at net.codestory.http.routes.RouteCollection.lambda$createContextToPayload$51719a14$1(RouteCollection.java:593)
at net.codestory.http.routes.RouteCollection.apply(RouteCollection.java:567)
at net.codestory.http.AbstractWebServer.handleHttp(AbstractWebServer.java:152)
at net.codestory.http.internal.SimpleServerWrapper.handle(SimpleServerWrapper.java:71)
at org.simpleframework.http.socket.service.RouterContainer.handle(RouterContainer.java:106)
at org.simpleframework.http.core.RequestDispatcher.dispatch(RequestDispatcher.java:121)
at org.simpleframework.http.core.RequestDispatcher.run(RequestDispatcher.java:103)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

Do you have any ideas of why do I have such an issue?
Seems like use a NAS can be the reason but I really would you to use it.
I also try JBOD or SHR or RAID0 with no success...

If i try to re add document, same issue...40.1K documents maximum...
 noticed one thing.

If I use a Synology SMB :
Max files indexed by datashare = 17K
If I use a Windows mapping
Max files indexed by datashare = 40.1K
If I use a symlink
Max files indexed by datashare = 40.3K

Strange...Do you have any recommendation?
Thanks a lot for your help and reply.

Best regards,

**Comment by Hermano123** [comment]
Hi!

No idea? :-(
thanks

**Comment by Hermano123** [comment]
Hi!
Seems like I found the issue.
I have some files in the following format : Word 2 and earlier binary documents and templates
Could you please confirm datashare is not able te read them?

By default that kind of files are blocked by Microsoft Word for example.
Best regards,
